### ISSUE TITLE
suggest new requirement for 2.4.6

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1001]
Suggest new requirement 2.4.6

**Use Argon2id with a minimum configuration of 15 MiB of memory, an iteration count of 2, and 1 degree of parallelism.**

and delete requirement 2.4.4

Reference: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

**Comment by ThunderSon** [comment]
How about having an appendix section that takes into consideration several PHF, and the requirement then becomes one, to use the most fitting PHF to their use case, or if they are using one, how to achieve their highest security levels.
Using bcrypt is not insecure, but using argon2id has benefits in X and Y, etc.
What if a system is running on scrypt, do we tell them "Change to another algo because this is insecure", or "ensure you use secure params for this algo"?

Plus, these parameters will always be changing, maybe even faster than ASVS versions, so that could help release it from that, and make it follow the best practices at any given time.

**Comment by jmanico** [comment]
I ended up going down this route and making big changes to 2.4 making this issue moot.
