### ISSUE TITLE
3.5.3 error

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1012]
Encryption should be removed from the requirement as its not needed to stop the listed attacks and is not default in JWT's

**Comment by elarlang** [comment]
V3.5 Token-based Session Management
* 3.5.3 Verify that stateless session tokens use digital signatures, encryption, and other countermeasures to protect against tampering, enveloping, replay, null cipher, and key substitution attacks.

**Comment by lfservin** [comment]
My take is
 * digital signature would prevent tampering and enveloping, null cipher and key substitution attacks
 * transport encryption would help versus replay, because an attacker wouldn't have the jwt to replay

if encryption is causing trouble I would redefine it as "transport encryption" rather than just encrpytion.

**Comment by elarlang** [comment]
"encryption" was removed from the requirement via https://github.com/OWASP/ASVS/commit/771a33a1c2d1ce52190b1d4c970e20e1c526afc7
