### ISSUE TITLE
2.2.7 and 2.3.2 are duplicate (somewhat)

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1013]
Both of these requirements address FIDO for authentication and looks somewhat dupliicated

**Comment by elarlang** [comment]
V2.2 General Authenticator Security
* 2.2.7 Verify intent to authenticate by requiring the entry of an OTP token or user-initiated action such as a button press on a FIDO hardware key.

V2.3 Authenticator Lifecycle
* 2.3.2 Verify that enrollment and use of subscriber-provided authentication devices are supported, such as a U2F or FIDO tokens.

**Comment by jmanico** [comment]
I propose removing 2.2.7 and just leaving 2.3.2 cc @elarlang

**Comment by cmlh** [comment]
These are discrete tasks undertaken during the lifetime of FIDO and therefore should be separate requirements verified by ASVS.

**Comment by tghosth** [comment]
I think this needs to revisited to be sure that these are definitely duplicates. 

As @belalena points out in #1520, we also need to consider the levels.

**Comment by tghosth** [comment]
I have opened #1683 to revert this change.

I think that these do represent two separate processes but I think they could be clarified. I suggest that we resolve this as part of the rework of this chapter.

**Comment by tghosth** [comment]
2.2.7 seems like a principle rather than a requirement. For OTPs, how else are you going to authenticate without entering an OTP, for push notifications we should handle this point with #1415, for hardware, we should add this point to [2.2.4](https://github.com/OWASP/ASVS/blob/7c72f34f8f4b3c7221975ec1460b76103bdee2f6/5.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security).

Proposal:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.4** | [MODIFIED, SPLIT TO 2.2.9, MERGED FROM 2.2.7] Verify that a hardware-based authentication mechanism is used that provides verifier impersonation resistance against phishing attacks (such as WebAuthn) and verifies intent to authenticate by requiring a user-initiated action (such as a button press on a FIDO hardware key). | | | ✓ | 308 | 4.3.1 |
| **2.2.7** | [DELETED, MERGED TO 2.2.4] | | | | | |

**Comment by tghosth** [comment]
@jmanico

**Comment by tghosth** [comment]
Get rid of required.

**Comment by jmanico** [comment]
I agree with your last major comment, Josh. I like deleting 2.2.7 and 2.3.2as well as your modification to 2.2.4.
