### ISSUE TITLE
2.10.* has incorrect NIST section

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1025]
2.10.1, 2.10.2, 2.10.3, 2.10.4 all reference NIST section 5.1.1.1. NIST section 5.1.1.1 is titled "Memorized Secret Authenticators":

> Memorized secrets SHALL be at least 8 characters in length if chosen by the subscriber. Memorized secrets chosen randomly by the CSP or verifier SHALL be at least 6 characters in length and MAY be entirely numeric. If the CSP or verifier disallows a chosen memorized secret based on its appearance on a blacklist of compromised values, the subscriber SHALL be required to choose a different memorized secret. No other complexity requirements for memorized secrets SHOULD be imposed. A rationale for this is presented in Appendix A Strength of Memorized Secrets.

This is not applicable to API keys. It says nothing about unchanging credentials, default credentials, or password storage.

**Comment by Sjord** [comment]
See also #397. I could not find applicable NIST sections.

**Comment by jmanico** [comment]
Would you like to submit a PR on this to fix the problem or is it to big?

**Comment by jmanico** [comment]
Pardon @jimfenton do any of these have NIST categories? We think the 5.1.1.1 reference is off. We would be grateful for your eyeballs on this. :)

```
| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---:| :---: | :---: | :---: |
| **2.10.1** | Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys or shared accounts with privileged access. | | ✓ | ✓ | 287 | 5.1.1.1 |
| **2.10.2** | Verify that if passwords are required for service authentication, the service account used is not a default credential. (e.g. root/root or admin/admin are default in some services during installation). | | ✓ | ✓ | 255 | 5.1.1.1 |
| **2.10.3** | Verify that passwords are stored with sufficient protection to prevent offline recovery attacks, including local system access. | | ✓ | ✓ | 522 | 5.1.1.1 |
| **2.10.4** | Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |
```

**Comment by jimfenton** [comment]
2.10.1: I'm not sure I understand this one: what is an "unchanging credential"? Does this mean that the credential (authentication secret) can't be changed, or that it isn't routinely changed? SP 800-63 deals with authentication of users, not APIs, but I don't see what should be used instead of a static API key (with enough entropy, of course).

2.10.2: This is covered in SP 800-53 rev 5. Check control IA-5 there.

2.10.3: See 800-63B Section 5.1.1.2, last 4 paragraphs.

2.10.4: Again more of an SP 800-53 issue, probably closest to IA-5 but I haven't found anything that maps closely to this requirement (although it is a good one).

**Comment by Sjord** [comment]
> 2.10.1: I'm not sure I understand this one

Me neither. See also #1032.

> 2.10.3: See 800-63B Section 5.1.1.2, last 4 paragraphs.

Section 2.10 is about services authenticating to each other, e.g. a web server authenticating to a database server. In that case, the credential is more of a secret key than a "memorized secret". Also, the plaintext credential is required, so hashing it with PBKDF2 is not an option.

**Comment by tghosth** [comment]
Hi @Sjord, do you have a proposed update based on this discussion?

**Comment by jimfenton** [comment]
Yes, API keys have different requirements from memorized secrets. SP 800-63B deals with the authentication of (human) subjects and not particularly with authentication of APIs, so there isn't a direct correlation to a section in 800-63B.

800-63B does, however, deal with keys in several places (seeds for OTP authenticators, for example: section 5.1.4.1). It generally requires a key to have the minimum security strength specified in SP 800-131A, which is currently 112 bits. My personal recommendation would be that an API key be randomly chosen, have at least 112 bits of entropy, and that the verifier should be a hash of that key. Salting should not be necessary because the risk of collisions and brute force attacks is negligible at that key size.

**Comment by Sjord** [comment]
I propose to remove the references and the column. The column currently only allows referencing sections in SP800-63B. It is possible that other NIST guidelines provide better recommendations for keys, but we currently don't have a good way to reference those. so I propose to remove the column, until we come up with a more structural approach in [ASVS v5.0 - mappings to other standards · Issue #1167 · OWASP/ASVS](https://github.com/OWASP/ASVS/issues/1167).

**Comment by tghosth** [comment]
@Sjord please open a PR for removing the reference although we will not remove the whole column for now

**Comment by tghosth** [comment]
PR merged
