### ISSUE TITLE
Move 8.3.4 to V1, merge with 1.8.1

### ISSUE THREAD

**Issue by Sjord** [OWASP/ASVS#1064]
> V8 Data Protection
> V8.3 Sensitive Private Data
> 8.3.4: Verify that all sensitive data created and processed by the application has been identified, and ensure that a policy is in place on how to deal with sensitive data.

> V1.8 Data Protection and Privacy Architecture
> 1.8.1: Verify that all sensitive data is identified and classified into protection levels.

8.3.4 is really a non-technical requirement, and really similar to 1.8.1.

**Comment by jmanico** [comment]
I suggest we just drop 1.8.1 and call it a duplicate. This is so clear, I say we go to PR.

**Comment by elarlang** [comment]
Proposal - merge 8.3.4 to 1.8.1 like @Sjord originally proposed.

Mostly used current 8.3.4, added one phrase from current 1.8.1:
> V1.8.1 Verify that all sensitive data created and processed by the application has been identified **and classified into protection levels**, and ensure that a policy is in place on how to deal with sensitive data.

**Comment by jmanico** [comment]
Yep this is definitely an architecture/threat modeling requirement that belongs in a "secure design" or architecture category. This is a very important requirement that belongs in v1. Good proposal.

I like your new v1.8.1, I think we are close to a PR.

**Comment by elarlang** [comment]
Started to make PR for this, but found some more questions to solve.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.8.1** | Verify that all sensitive data is identified and classified into protection levels. | | ✓ | ✓ | |
| **8.3.4** | Verify that all sensitive data created and processed by the application has been identified, and ensure that a policy is in place on how to deal with sensitive data. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 200 |


Some more decision points:

* **level**
  * 1.8.1 level 2
  * 8.3.4 level 1
  * from potential v4.0.4 point of view it's a breaking change (as 8.3.4 will be removed and therefore contains level change compared to 1.8.1)
  * as 1.8.1 will be pre-condition for every requirement which contains "sensitive data", then I propose it to be level 1 (level itself is topic to discuss for v5.0)
* **cwe**
  * 1.8.1 is missing CWE 
  * 8.3.4 has [CWE-200](https://cwe.mitre.org/data/definitions/200.html) "CWE-200: Exposure of Sensitive Information to an Unauthorized Actor"
  * CWE-200 is "just exposing sesitive information" and feels wrong for this requirement
  * proposal is to use [CWE-213](https://cwe.mitre.org/data/definitions/213.html) "CWE-213: Exposure of Sensitive Information Due to Incompatible Policies"
* **proactive control**
  * 1.8.1 does not have any
  * 8.3.4 points to [C8](https://owasp.org/www-project-proactive-controls/#div-numbering)
  * do we keep and need them?


# Proposals

## For v5.0

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.8.1** | [MODIFIED, MERGED FROM 8.3.4, LEVEL 2 > 1] Verify that all sensitive data created and processed by the application has been identified and classified into protection levels, and ensure that a policy is in place on how to deal with sensitive data. | ✓ | ✓ | ✓ | 213 |
| **8.3.4** | [DELETED, MERGED TO 1.8.1] | | | | |

## For v4.0.4

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---:| :---: | :---: |
| **1.8.1** | Verify that all sensitive data is identified and classified into protection levels. | | ✓ | ✓ | 213 |
| **8.3.4** | Verify that all sensitive data created and processed by the application has been identified, and ensure that a policy is in place on how to deal with sensitive data. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 213 |

**Comment by Sjord** [comment]
Level: I think it should be level 1, because classifying data is fundamental to securing it. Perhaps it is not L1 because it's not pentestable?

CWE: CWE-200 is very generic, and CWE-213 is pretty specific. I am not sure which is better. I think both are acceptable.

Proactive controls: C8 talks about data classification, so I think it's relevant here.

**Comment by tghosth** [comment]
Merged
