### ISSUE TITLE
2.4.4 - pre-hash requirement for bcrypt for long passwords?

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1090]
[2.4.4](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v24-credential-storage)

> Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10.

Issue is "spin off" from discussion in https://github.com/OWASP/ASVS/issues/756#issuecomment-642144272

Proposal from @tghosth is not implemented and the question is - is it so by accident?

> V2.4.4 Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow (typically at least 13) **and passwords are pre-hashed to avoid truncation issues**.

**Comment by jmanico** [comment]
One, there is the problem is password shucking
https://www.scottbrady91.com/authentication/beware-of-password-shucking#:~:text=Password%20shucking%20is%20a%20method,it%20to%20its%20weaker%20algorithm.

Two, prehashing is not as simple as it looks.  From https://security.stackexchange.com/questions/61595/is-it-good-practice-to-sha512-passwords-prior-to-passing-them-to-bcrypt

You still want to exercise caution about some practical details. In particular, many bcrypt implementations expect a password, i.e. a sequence of characters, terminating with the first byte of value 0x00. The output of SHA-512 is binary and thus may contain some bytes of value 0x00. For instance, 1/256th of all passwords will yield a hash value which begins with a byte of value 0x00, that a string-based bcrypt instance will understand as equivalent to an empty password.

**Comment by jmanico** [comment]
The password section is heavily modified and in parity with https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html - please open a new issue if you want to make major changes. I am happy to adjust 2.4.4 and add the 72-byte limit.

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---:| :---: | :---: | :---: |
| **2.4.1** | [MODIFIED] Verify that one of the following password hashing functions is used when storing passwords: argon2id, scrypt, bcrypt or PBKDF2. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.2** | [DELETED] | | | | | |
| **2.4.3** | [MODIFIED] Verify that if PBKDF2 is used, the iteration count SHOULD be as large as verification server performance will allow, with a minimum of 720,000 iterations with PBKDF2-HMAC-SHA1, a minimum of 310,000 iterations using PBKDF2-HMAC-SHA-256, or with a minimum of 120,000 iterations with PBKDF2-HMAC-SHA-512. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.4** | [MODIFIED] Verify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.5** | [DELETED] | | | | | |
| **2.4.6** | [ADDED] Verify that if argon2id is used, the configuration SHOULD be as strong as verification server performance will allow, with a minimum configuration of 15 MiB of memory, an iteration count of 2, and 1 degree of parallelism. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
| **2.4.7** | [ADDED] Verify that if scrypt is used, the configuration SHOULD be as strong as verification server performance will allow, with a minimum CPU/memory cost parameter of (2^16), a minimum block size of 8 (1024 bytes), and a parallelization parameter of 1. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | | ✓ | ✓ | 916 | 5.1.1.2 |
