### ISSUE TITLE
autocomplete field conflict

### ISSUE THREAD

**Issue by ordinaehs** [OWASP/ASVS#111]
In the new ASVS 3.0.1, V2.2 was changed to include the storage of the plaintext credentials. However, V9.1 explicitly mentions autocomplete-functionality. In other words, there's now a large overlap between V2.2 and V9.1, with V9.1 being completely contained within V2.2. Can this ambiguity please be resolved?

**Comment by vanderaj** [comment]
2.2 is about *applications* storing reversible passwords, which implies improper plain text equivalent storage of credentials, which happens regardless of if a browser caches the password. https://cwe.mitre.org/data/definitions/257.html

9.1 is about *browsers* caching form fields, particularly password fields. Unfortunately, it does not contemplate autocomplete=off being utterly ignored by modern browsers. This can be avoided by the use of Ajax submission that doesn't allow a direct POST. https://cwe.mitre.org/data/definitions/525.html

Does this help? They are very different things, although to the end user sitting behind a browser, may not seem so. I am all for end user's controlling the security choices, such as employing a password manager, but ASVS cannot assume that browsers do one thing and ask for another as we've already seen a major change in behavior since the ASVS was written. 

https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/wYGThW5WRrE

Many large financial firms want autocomplete=off to stay, and it's possible to do so with Ajax emulation of this by obfuscating to the browser that the form is indeed a login form. However, as a user of password managers, I do feel that having to copy and paste my username + very long and random password is a hassle. 

Does 9.1 need to change to be about a solid anti-caching header? If so, we already have that in 9.4, in which case, does 9.1 go away?

Thoughts

**Comment by ordinaehs** [comment]
Ah, I see where my confusion came from. Yes, those are indeed totally different. May I suggest:
Verify that forms containing credentials are not filled in by the application **using server-side information**. Pre-filling by the application implies that credentials are stored in plaintext or a reversible format, which is explicitly prohibited.
or something along those lines? This makes the distinction explicit.

Personally, I would not change V9.1 or V9.4. If browsers do not implement autocomplete correctly, I would consider that a problem of the client, not the application developer. Maybe consider adding a higher-level item that somehow encompasses these concerns?

**Comment by vanderaj** [comment]
Thank you for the report. Fixed 2.2 in milestone 3.1
