### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by andrettv** [OWASP/ASVS#1310]
https://github.com/andrettv/ASVS/commit/6f8d0720b6f9b8f19f5e458a62a21e1c661dd802

**Comment by elarlang** [comment]
## No extra content and links to requirement text

Please keep only those links in requirements which are already there and keep it exactly with the same format. No additional links.

Example (extra WSTG-SDLC link):
```
| **1.1.1** | Убедитесь в использовании безопасного жизненного цикла разработки программного обеспечения, который обеспечивает безопасность на всех этапах разработки. ([C1](https://owasp.org/www-project-proactive-controls/v3/en/c1-security-requirements)) ([WSTG-SDLC](https://owasp.org/www-project-web-security-testing-guide/stable/3-The_OWASP_Testing_Framework/0-The_Web_Security_Testing_Framework)) | | ✓ | ✓ | |
```

Reasons:
* markdown is for "plain text", it is the input for format for all other formats - if we need links to some output format, we generate them with export tools, see https://github.com/OWASP/ASVS/issues/810
* no extra mapping to requirement - all translations should follow exactyle the same format and content as original, all extra mapping should go to separate mapping files (separate project), see https://github.com/OWASP/ASVS/issues/1167


## CWE just a number

Keep CWE just a number, the same reasons like described above.

## NIST

And the same with links to NIST.

**Comment by andrettv** [comment]
Done (https://github.com/andrettv/ASVS/commit/8ef9b7a7b8d8203c72d743c9a148987b1d1f9ad7)

**Comment by elarlang** [comment]
Feedback is basically "keep all the mistakes from English version" :)

## Markdown syntax

Please do not use markdown syntax in requirement text for formating, the reason is the same like with links - in github and markdown is just our input text and we use it for different other formats (plain text in JSON, CSV, PDF, ...)

Example:
* 1.12.2 - `MIME-type: application/octet-stream`
* 5.2.4 - `eval()`
* 5.2.7 - `foreignObject`
* 5.5.4 -  `JSON.parse`, `eval()`
* 13.1.5 - `HTTP 406 Unacceptable`, `HTTP 415 Unsupported Media Type`
* 13.2.5 -  `Content-Type`, `application/xml`, `application/json`
* 14.4.1 - `Content-Type`, `text/*`, `/+xml`, `application/xml` - `charset=UTF-8`, `ISO-8859-5`, `Content-Type`
* 14.4.2 - `Content-Disposition: attachment; filename="api.json"`
* 14.4.3 - `Content Security Policy`
* 14.4.4 - `X-Content-Type-Options: nosniff`
* 14.4.5 - `Strict-Transport-Security`, `Strict-Transport-Security: max-age=15778463; includeSubDomains`
* 14.4.6 - `Referrer-Policy`, `Referer`
* 14.4.7 - `Content-Security-Policy: frame-ancestors`, `X-Frame-Options`
* 14.5.3 - `Access-Control-Allow-Origin`, `"null"`
* 14.5.4 - `bearer`

## Links

NIST link still exists for 3.3.2


## CWE value

CWE value for 3.4.3 in English version is 16 and in translation is 1275.

1275 is better value than 16 and it is corrected for 5.0, but translated document must contain all the same data like original document. Please keep all the same values like in original, even those are wrong or outdated.


## Testing guide link

In English version:

```
[OWASP Testing Guide 4.0: Authorization](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/05-Authorization_Testing/README.html)
```

In Russian version:
```
[OWASP Testing Guide 4.0: Authorization](https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/05-Authorization_Testing/README.html)
```

In translated version it points to stable release, if WSTG creates release 5, it will point to release 5 instead of release 4. It's not correct in English version as well :/


## Empty paragraphs

You have removed empty paragraph from V3 and V4:
```
## Security Verification Requirements

## V3.1 Базовые требования
```

I can understand the reason and I was removing them for 5.0 (https://github.com/OWASP/ASVS/issues/968), but for translation, it must keep the same structure like original one. Basically I ask you to keep all the mistakes from English version - then it's easier to validate the document structure and make the exports, because those are producing the same output then.


## Removed paragraphs

V6, V7, V8, V9 are missing "Control Objective" paragraph
```
# V6 Хранимая криптография

## Control Objective
```

Please keep the structure like it is in English version

## V7.2 missing some translated lines?

This part from V7.2 does not exist in translated document
```
V7.2 covers OWASP Top 10 2017:A10. As 2017:A10 and this section are not penetration testable, it's important for:

* Developers to ensure full compliance with this section, as if all items were marked as L1
* Penetration testers to validate full compliance of all items in V7.2 via interview, screenshots, or assertion
```


## Link in 8.3.4

C8 link in 8.3.4 decription in English version
```
[C8](https://owasp.org/www-project-proactive-controls/#div-numbering)
```

In Russian version:
```
[C8](https://owasp.org/www-project-proactive-controls/v3/en/c8-protect-data-everywhere.html)
```

**Comment by elarlang** [comment]
If the PR is merged (@tghosth will handle this part) then we put translator(s) information to README.md.

Previous version was translated by Sergey Diakonov, did you used v4.0.2 as the base and now translators should be Sergey Diakonov and Andrei Titov?

**Comment by andrettv** [comment]
No, mine is based on English version 4.0.3 from the scratch and not on mentioned 4.0.2 translation as the former was a pure automatic Yandex.Translate proceedings or something like that.

**Comment by tghosth** [comment]
All merged in, thanks @andrettv

**Comment by andrettv** [comment]
Thanks @tghosth, 
Please correct the link on https://owasp.org/www-project-application-security-verification-standard/ on v.4.0.3.

**Comment by tghosth** [comment]
🤦‍♂️oops, thanks for pointing that out, it should be roll out a fix shortly
