### ISSUE TITLE
2.5.5 is a duplicate of 2.2.3

### ISSUE THREAD

**Issue by thomasdax98** [OWASP/ASVS#1416]
From my understanding, [2.5.5](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v25-credential-recovery) is already included in [2.2.3](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security). Therefore, 2.5.5 could be removed.

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.2.3** | [MODIFIED, SPLIT TO 2.2.10] Verify that users are notified after updates to authentication details, such as credential resets or modification of the username or email address. | ✓ | ✓ | ✓ | 778 | 6.1.2 |
 **2.5.5** | Verify that if an authentication factor is changed or replaced, that the user is notified of this event. | ✓ | ✓ | ✓ | 304 | 6.1.2.3 |

**Comment by elarlang** [comment]
Just for information, used CWE values:
* [CWE-778](https://cwe.mitre.org/data/definitions/778.html) - Insufficient Logging
* [CWE-304](https://cwe.mitre.org/data/definitions/778.html) - Missing Critical Step in Authentication

**Comment by mgargiullo** [comment]
> * Insufficient Logging

I'd argue that we have the wrong CE listed there.  CWE 778 is covered in 7.1.3, 7.1.4, & 7.2.1 (Logging of events)

2.2.3 & 2.5.5 is about notifying the user. (CWE-304)

Since the change of language in 2.2.3 between v4.0.3 and v5 removed the key differentiator between these two issues, they essentially say the same thing now.

2.2.3: v4.0.3
Verify that secure notifications are sent to users after updates to authentication details, such as credential resets, email or address changes, logging in from unknown or risky locations. The use of push notifications - rather than SMS or email - is preferred, but in the absence of push notifications, SMS or email is acceptable as long as no sensitive information is disclosed in the notification.

2.2.3: v5.0
Verify that users are notified after updates to authentication details, such as credential resets or modification of the username or email address.

Since in v5.0 the wording of 2.2.3 & 2.5.5 are arguably the same, the difference is now in 2.2 vs. 2.5 section language (General authenticator security vs. Credential recovery)

**Comment by tghosth** [comment]
@set-reminder 1 week look at this

**Comment by tghosth** [comment]
Ok, long story short, 2.2.3 is about generally alerting the user when there is sensitive activity in their account which I don't think is restricted to just authentication data and seems connected to the general security logging discussion I had directly with @elarlang. Likelihood is that we will need to integrate it into a large requirement.

In this context 2.5.5 is not a duplicate as it refers to specifically when a credential is rotated/recovered.

**Comment by tghosth** [comment]
Overall I think we need to wait for the outcome of #1444

**Comment by belalena** [comment]
Any update here? 

From my mind 
2.2.3 is about changes to authentication details:
- credentials (e.g., password resets) 
- updates to identification information (e.g., username or email address). 
2.5.5. is about changes to authentication factors: 
- switching from password-only to multi-factor authentication
- adding factor
- removing factor

Why not to merge 2.2.3 and 2.5.5.? 

For instance:

 Verify that users are notified of any updates to their authentication details and authentication factors.

**Comment by elarlang** [comment]
@tghosth - if you don't have good arguments against it, I support the idea to merge 2.5.5 to 2.2.3 and change 2.2.3.

Current CWE for 2.2.3 is clearly wrong. I'm not sure CWE-304 is the correct one either: "CWE-304 Missing Critical Step in Authentication"
_Authentication techniques should follow the algorithms that define them exactly, otherwise authentication can be bypassed or more easily subjected to brute force attacks._

**Comment by elarlang** [comment]
and I'm not sure why it waits for logging reorg? Yes, all detections should be logged, but also those should be notified...

**Comment by tghosth** [comment]
OK, I am prepared to accept that 2.5.5 is a duplicate.

I still think that this is sort of a logging thing but I guess we can leave that to the dedicated issue.

I don't know that the CWE should be as I am not sure there is a CVE for insufficient security alerting....
