### ISSUE TITLE
New Requirement on Sessions

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1417]
A requirement as follows may be prudent.

_Make sure all active sessions or tokens are revoked when a user account is terminated or deleted (such as an employee leaving the company)._

**Comment by elarlang** [comment]
It take content from other similar requirement #1418 :
_If you are using the access control mechanism of JWT's then be certain to revoke current active tokens when admins change the entitlements/roles of a user._

In my opinion it makes sense to combine them to one requirement or at least handle together.

**Comment by tghosth** [comment]
I will take a stab at this

@set-reminder 5 weeks look at this

**Comment by tghosth** [comment]
I think it is hopefully clear that section 3 requires the ability to logout and invalidate the session token, even if this is a JWT.

I don't however agree that these should be combined as I think they handle slightly different cases. The issue from #1418 is specifically relevant when using the contents of JWTs and other stateless tokens to make access control decisions. I was also wondering this requirement should be in chapter V4 because it is about access control but I think that given the key action here is on the session identifier, section 3 is probably more appropriate.

As such, I would suggest the following:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **[3.3.6](https://appsecg.host/3.3)** | [ADDED] Verify that all active sessions are revoked when a user account is disabled or deleted (such as an employee leaving the company). | ✓ | ✓ | ✓ | 613 | |
| **[3.5.7](https://appsecg.host/3.5)** | [ADDED] Verify that all active stateless tokens, which are being relied upon for access control decisions, are revoked when admins change the entitlements/roles of the user. | ✓ | ✓ | ✓ | 613 | |

@jmanico @elarlang What do you think?

**Comment by jmanico** [comment]
> I think it is hopefully clear that section 3 requires the ability to logout and invalidate the session token, even if this is a JWT.
> 
> I don't however agree that these should be combined as I think they handle slightly different cases. The issue from #1418 is specifically relevant when using the contents of JWTs and other stateless tokens to make access control decisions. I was also wondering this requirement should be in chapter V4 because it is about access control but I think that given the key action here is on the session identifier, section 3 is probably more appropriate.
> 
> As such, I would suggest the following:
> 
> #	Description	L1	L2	L3	CWE	[NIST §](https://pages.nist.gov/800-63-3/sp800-63b.html)
> **[3.3.6](https://appsecg.host/3.3)**	[ADDED] Verify that all active sessions are revoked when a user account is disabled or deleted (such as an employee leaving the company).	✓	✓	✓	613	
> **[3.5.7](https://appsecg.host/3.5)**	[ADDED] Verify that all active stateless tokens, which are being relied upon for access control decisions, are revoked when admins change the entitlements/roles of the user.	✓	✓	✓	613	
> @jmanico @elarlang What do you think?

This looks fantastic, Josh. I love it! :)

**Comment by tghosth** [comment]
I opened a PR with my changes

**Comment by tghosth** [comment]
Note that the added 3.5.7 ended up being removed and replaced with the more goal focused 4.1.6 (https://github.com/OWASP/ASVS/issues/2059#issuecomment-2449640432, #2210)
