### ISSUE TITLE
13.2.1 is not clear to me

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1485]
I don't really understand this requirement.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.2.1** | Verify that enabled RESTful HTTP methods are a valid choice for the user or action, such as preventing normal users using DELETE or PUT on protected API or resources. | ✓ | ✓ | ✓ | 650 |

[CWE-650](https://cwe.mitre.org/data/definitions/650.html) seems to focus on a slightly different point although I think it is still important:

> The HTTP GET method and some other methods are designed to retrieve resources and not to alter the state of the application or resources on the server side. Furthermore, the HTTP specification requires that GET requests (and other requests) should not have side effects. Believing that it will be enough to prevent unintended resource alterations, an application may disallow the HTTP requests to perform DELETE, PUT and POST operations on the resource representation. However, there is nothing in the HTTP protocol itself that actually prevents the HTTP GET method from performing more than just query of the data. Developers can easily code programs that accept a HTTP GET request that do in fact create, update or delete data on the server. For instance, it is a common practice with REST based Web Services to have HTTP GET requests modifying resources on the server side. However, whenever that happens, the access control needs to be properly enforced in the application. No assumptions should be made that only HTTP DELETE, PUT, POST, and other methods have the power to alter the representation of the resource being accessed in the request.

I need to review the history here but I think it needs making more specific.

@set-reminder 4 weeks @tghosth to review

**Comment by elarlang** [comment]
If it's authorization problem, then it's covered/duplicate of 13.1.4

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.1.4** | Verify that authorization decisions are made at both the URI, enforced by programmatic or declarative security at the controller or router, and at the resource level, enforced by model-based permissions. | | ✓ | ✓ | 285 |

Watching mapped CWE (650), I think the idea of the requirements should be that used methods follow strictly idea of RESTful way of using HTTP methods and with safe HTTP methods you can not do any state changes. For that we have added new requirement (with the same CWE):

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **14.5.5** | [ADDED] Verify that HTTP requests using the HEAD, OPTIONS, TRACE or GET verb do not modify any backend data structure or perform any state-changing actions. These requests are safe methods and should therefore not have any side effects. | ✓ | ✓ | ✓ | 650 |

As the problem is not API specific, I would change the label of 14.5.5 from `ADDED` to `MODIFIED, MOVED FROM 13.2.1` and merge the points from both requirements (current 13.2.1 and 14.5.5)

**Comment by tghosth** [comment]
History:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.2.1** | Verify that enabled RESTful HTTP methods are a valid choice for the user or action, such as preventing normal users using DELETE or PUT on protected API or resources. | ✓ | ✓ | ✓ | 650 |
| **18.2** | Verify that, if REST is used, the HTTP Methods are a valid choice for the user, or action. |  | ✓ | ✓ | 650 |

This requirement was originally added in https://github.com/OWASP/ASVS/commit/7c706e27dfd6da86d4db34f9fe7255826765be6a. I cannot see a relevant issue.

I think the CWE makes it clearer what the purpose of the requirement is and that the updated/most-recent wording is a little confusing.

Previously @VincentDS [said](https://github.com/OWASP/ASVS/issues/672#issuecomment-531662744):

> For me, V13.2.1 is more about restricting unsafe methods on protected API endpoints...

Whilst I accept it was [technically my idea 🤦‍♂️](https://github.com/OWASP/ASVS/issues/672#issuecomment-533263387), I am not sure this actually requires a new requirement as based on CWE 650 I think this is a specific problem which is covered by the new 14.5.5. I don't think 13.2.1 really addresses a specific problem. 

As such, @elarlang I agree with your proposal:

> As the problem is not API specific, I would change the label of 14.5.5 from `ADDED` to `MODIFIED, MOVED FROM 13.2.1` and merge the points from both requirements (current 13.2.1 and 14.5.5)

13.2.1 would change to [DELETED, MOVED TO 14.5.5]

Anyone with further comments?

**Comment by tghosth** [comment]
@set-reminder 6 weeks @tghosth to address if no further comments.

**Comment by jmanico** [comment]
A student of mine commented that 13.1.4 is hard to dissect and may need to be broken up.

13.1.4 | Verify that authorization decisions are made at both the URI, enforced by programmatic or declarative security at the controller or router, and at the resource level, enforced by model-based permissions. |   | ✓ | ✓ | 285
-- | -- | -- | -- | -- | --

**Comment by tghosth** [comment]
> A student of mine commented that 13.1.4 is hard to dissect and may need to be broken up.
>
> 13.1.4 | Verify that authorization decisions are made at both the URI, enforced by programmatic or declarative security at the controller or router, and at the resource level, enforced by model-based permissions. |   | ✓ | ✓ | 285
> -- | -- | -- | -- | -- | --

@jmanico we are going to try and handle this in #1312

**Comment by tghosth** [comment]
Created a PR #1627 and waiting for approval
