### ISSUE TITLE
JNDI injection prevention checks should be added to the ASVS list

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1533]
The application should prevent JNDI injection attacks by properly validating and sanitizing user input before using it in a JNDI query. (We have items for SQL injection, LDAP injection, SMTP injection,... but we don't have an item for JNDI injection)

Rationale:

JNDI injection is a type of attack that occurs when an attacker is able to inject malicious data into the JNDI data source used by an application, allowing them to execute arbitrary code on the application server. Proper validation and sanitization of user input can prevent this type of attack by ensuring that only safe data is used in JNDI queries.

Remediation:

Validate user input by checking that it conforms to the expected format, length, and range of values.
Use parameterized JNDI queries to prevent malicious data from being interpreted as part of the query.
Sanitize user input by removing or encoding special characters that could be used to inject malicious data into the JNDI query.
Review and test the application's input validation and sanitization mechanisms to ensure they are properly implemented and effective.

Testing Method:

- Verify that the application properly validates and sanitizes the input before using it in the JNDI query.

References:

[Exploiting JNDI Injections](https://www.veracode.com/blog/research/exploiting-jndi-injections-java)

**Comment by tghosth** [comment]
Need to investigate the V5 section and see whether this fits in there somewhere.

**Comment by tghosth** [comment]
How about:

> Verify that if the application allows untrusted input to be used with Java Naming and Directory Interface (JNDI) queries, it sanitizes the content before use.

 @ImanSharaf  @elarlang @jmanico

**Comment by elarlang** [comment]
ok for me

**Comment by jmanico** [comment]
Small cleanup.

5.2.11 | [ADDED] Verify that the application securely handles untrusted input in Java Naming and Directory Interface (JNDI) queries by employing input sanitization techniques. | ✓ | ✓ | ✓
-- | -- | -- | -- | --


<br class="Apple-interchange-newline">

**Comment by ImanSharaf** [comment]
The phrase "securely handles" is rather vague. It might be more precise to explicitly state what kind of threat or vulnerability we are trying to mitigate.

I would propose this one @tghosth 

5.2.11 | [ADDED] Verify that the application prevents Java Naming and Directory Interface (JNDI) injection attacks by validating and appropriately encoding untrusted input before use in JNDI queries. | ✓ | ✓ | ✓
-- | -- | -- | -- | --

**Comment by jmanico** [comment]
This is a super important requirement, it would have stopped Log4shell.

**Comment by elarlang** [comment]
> This is a super important requirement, it would have stopped Log4shell.

chicken and egg thingy , without Log4shell no-one knows how important it is :)

Any other feedback or improvement or it is ready to go?

**Comment by jmanico** [comment]
> > This is a super important requirement, it would have stopped Log4shell.
> 
> chicken and egg thingy , without Log4shell no-one knows how important it is :)
> 
> Any other feedback or improvement or it is ready to go?

Not true. Alvaro munoz has been talking about untrusted JNDI problems since 2016. It's a known Java-centric attack vector.

**Comment by elarlang** [comment]
(More of this offtopic:) Requirement in ASVS will not fix bugs, otherwise we should not have any so-called XSS, SQL injection etc long time already :)

**Comment by tghosth** [comment]
Having looked at all our suggestions, I would like to suggest the following as I prefer to have the requirement noted before what it prevents:

5.2.11 | [ADDED] Verify that the application appropriately sanitizes untrusted input before use in Java Naming and Directory Interface (JNDI) queries to prevent JNDI injection attacks. | ✓ | ✓ | ✓

@ImanSharaf I don't want to use the word "validates" as that sounds like input validation which shouldn't be a JNDI specific control. Jim also used the word sanitization which I think is appropriate unless you specifically think encoding is the correct term.

@jmanico @elarlang any final thoughts?

**Comment by elarlang** [comment]
Is there any encoding available for that?

Validation is not wrong by concept - you validate against allow-list what you execute. And if it is not possible to validate against allow-list, you need to sanitize.

I'm not expert on the topic, so I leave it for you.

**Comment by jmanico** [comment]
Here is an example in Java where validation really is the right defense.

![Screenshot 2023-09-26 at 1 02 23 PM](https://github.com/OWASP/ASVS/assets/531465/8b874225-4dd6-41a5-90fc-af36f1c0edf7)

**Comment by jmanico** [comment]
From ChatGTP: 

In the case of JNDI injection, the issue is not about safely including data in another context; it's about the unsafe invocation of a method (InitialContext.lookup() in this case) with untrusted data. Therefore, the primary defenses against JNDI injection are:

Input Validation: Whitelist the allowable JNDI references.
Least Privilege: Limit what the JNDI context can do.
Patch and Update: Keep your libraries and runtime up-to-date.
Why Encoding Doesn't Fit Here
Encoding is about taking data that could be interpreted in multiple ways and making sure it's interpreted in only one way. For example, you might encode < as &lt; in HTML to make sure it's interpreted as a text character and not as the start of an HTML tag. But in the case of JNDI injection, the problem isn't multiple interpretations; it's that the single interpretation (as a JNDI reference) is potentially dangerous.

A More Technical Dive
Let's get more technical for a moment. The InitialContext.lookup() method expects a String that represents a valid JNDI name. Encoding this String would not prevent it from being a valid JNDI name; it would just make it a different JNDI name. For instance, if you URL-encode the string, the lookup() method would still perform a lookup; it would just look up a different (encoded) name. This doesn't solve the problem; it just moves it.

The Right Tools for the Job
In security, it's crucial to use the right tool for the job. Encoding is a fantastic tool, but it's not the right one for preventing JNDI injection. For JNDI injection, the tools you want are input validation, least privilege, and patching—these are your hammers, saws, and screwdrivers for this particular job.

So, while encoding is a cornerstone of many security measures, it's not the go-to solution for every type of attack. Always assess the nature of the vulnerability you're dealing with and apply the appropriate mitigations. Keep those tools in your toolbox well-organized!

**Comment by tghosth** [comment]
> Here is an example in Java where validation really is the right defense.
> 
> ![Screenshot 2023-09-26 at 1 02 23 PM](https://user-images.githubusercontent.com/531465/270782577-8b874225-4dd6-41a5-90fc-af36f1c0edf7.jpg)

So @jmanico I would pendantically argue that input validation is verifying that input received matches the business logic expectations for a particular field whereas sanitization/encoding is either removing, transforming or rejecting data which is dangerous in a particular context. I accept that this particular examples sits on the border of that.

> You can also limit what JNDI can do:
> 
> ```
> Hashtable<String, String> env = new Hashtable<>();
> env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.rmi.registry.RegistryContextFactory");
> env.put(Context.PROVIDER_URL, "rmi://localhost:1099");
> InitialContext context = new InitialContext(env);
> ```
> 
> By setting the INITIAL_CONTEXT_FACTORY and PROVIDER_URL, you're limiting the types of services that the JNDI context can interact with.

I think these are good points and I would modify the requirement to say:

5.2.11 | [ADDED] Verify that the application appropriately sanitizes untrusted input before use in Java Naming and Directory Interface (JNDI) queries **and that JNDI is configured as securely as possible** to prevent JNDI injection attacks. | ✓ | ✓ | ✓
-- | -- | -- | -- | --

**Comment by jmanico** [comment]
Pattern matching with a RegEx is straight-up validation. This data is NOT being cleaned up (sanitization) or converted (encoded) in any way. If the pattern is not matched, the data is not used.

But I am being pedantic as well. I am happy with your proposed requirement so long as you are not preaching encoding to stop this attack, which would be wrong IMO.

**Comment by tghosth** [comment]
Thanks Jim, I think we are aligned :)

So @ImanSharaf any final comments on the following proposal:

5.2.11 | [ADDED] Verify that the application appropriately sanitizes untrusted input before use in Java Naming and Directory Interface (JNDI) queries and that JNDI is configured as securely as possible to prevent JNDI injection attacks. | ✓ | ✓ | ✓
-- | -- | -- | -- | --

**Comment by tghosth** [comment]
Opened #1736 to resolve this
