### ISSUE TITLE
Session management - 3.5.2 - Api keys

### ISSUE THREAD

**Issue by waleedfaridworkland** [OWASP/ASVS#1599]
Hello.

Hope you all are doing well.

We are looking to achieve ASVS level 2 compliance.

We have an upcoming project that requires machine to machine communication, and we are looking at implementing API keys for authenticating and identifying the request making entity.

The scope of these api keys would be limited to only a certain number of read only apis and would not work with all system wide apis.

Our requirement is quite specific in the sense that each API key would be associated with an organization entity rather than an individual user.

Now the problem is that under session management,  3.5.2 it states "Verify that the application uses session tokens rather than static API secrets and keys, except with legacy implementations.".

Does this specifically apply to user authentication and sessions only ?

Or does it apply to our use case of machine to machine api interaction as described above ? We do intend on adding certain security measures like IP restrictions on the use of these api keys. 

Any clarity on this matter would be highly appreciated ! Thank you.

**Comment by csfreak92** [comment]
I think this requirement mostly applies to user sessions. I believe I tested something similar before where machine to machine API interaction was implemented with API keys and seems fine as long as those API keys are well-protected (e.g. where/how are they kept, are these keys rotated regularly, access allowed by these keys, etc). As you mentioned, the API keys are limited to only a certain number of read-only APIs and not a system-wide access, so that sort of helps in tightening the implementation of it. 

These are my thoughts, but let's ask the community for their ideas about it. Cheers!

**Comment by elarlang** [comment]
Hi @waleedfaridworkland 

Seems that requirement 3.5.2 was not very clear and it 's addressed in separate issue https://github.com/OWASP/ASVS/issues/1522

The question itself got answered by @csfreak92 .

As the issue does not contain any proposal for changes in the requirement, I'll close the issue. If there are some proposals, please add them to already opened issue #1522
