### ISSUE TITLE
2.6.4 looks rather weak

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1615]
4 characters for a lookup secret (which is used in account recovery) looks SUPER weak and should be increased.

2.6.4 | [ADDED] Verify that lookup secrets have a minimum of 20 bits of entropy (typically 4 random alphanumeric characters or 6 random digits is sufficient). |   | ✓ | ✓ | 330 | 5.1.2.2
-- | -- | -- | -- | -- | -- | --

**Comment by mgargiullo** [comment]
@jmanico I agree with your assessment of 2.6.4. The list of pre-generated codes should have much higher entropy.  2.7.6 is a bit different. 2.7 talks about items like Google Authenticator or other TOTP tools. A six-digit numeric code has 25.8 bits of entropy, which is largely the norm now. 
 
I think 2.6.4 should be bumped to at least 50 bits of entropy. That's only a 32-digit numeric code. If a UUID4 is used, it bumps up to 128 bits.

As a side note... it makes sense to bump 2.7.6 to 25 bits of entropy?

**Comment by tghosth** [comment]
> 4 characters for a lookup secret (which is used in account recovery) looks SUPER weak and should be increased.

2.6.4 | [ADDED] Verify that lookup secrets have a minimum of 20 bits of entropy (typically 4 random alphanumeric characters or 6 random digits is sufficient). |   | ✓ | ✓ | 330 | 5.1.2.2
-- | -- | -- | -- | -- | -- | --

@jmanico This comes [straight from the NIST guidance](https://pages.nist.gov/800-63-3/sp800-63b.html#5121-look-up-secret-authenticators).

> 2.7.6 also looks weak and may be a duplicate of 2.6.4

2.7.6 | [MODIFIED] Verify that the initial authentication code is generated by a secure random number generator, containing at least 20 bits of entropy (typically 4 random alphanumeric characters or 6 random digits is sufficient). |   | ✓ | ✓ | 310 | 5.1.3.2
-- | -- | -- | -- | -- | -- | --

@jmanico Again. this comes [straight from the NIST guidance](https://pages.nist.gov/800-63-3/sp800-63b.html#5132-out-of-band-verifiers).


These points make me think we need to consider how we apply/interpret the NIST guidance going forward because I agree it is confusing.

I am going to leave this issue open but it should be handled in the major rework exercise for this chapter.

**Comment by jmanico** [comment]
NIST guidance here is very bad. NIST also suggests using social security numbers as a username. Let's me better than NIST!

**Comment by jmanico** [comment]
I'd like to suggest a change for 2.6.4/276

2.6.4 | [CHANGED] Verify that lookup secrets have a minimum of 128 bits of entropy (typically 22 random alphanumeric characters are sufficient). |   | ✓ | ✓ | 330 | 5.1.2.2
-- | -- | -- | -- | -- | -- | --

2.7.6 | [MODIFIED] Verify that the initial authentication code is generated by a secure random number generator, containing at least 128 bits of entropy (typically 22 random alphanumeric characters are sufficient). |   | ✓ | ✓ | 310 | 5.1.3.2
-- | -- | -- | -- | -- | -- | --

**Comment by jmanico** [comment]
If you like my suggestions here I am happy to go for a PR. cc @elarlang @tghosth

**Comment by tghosth** [comment]
I don't think we want a PR at this point, I think this is going to have to be considered in a wider context when we rewrite V2.

**Comment by tghosth** [comment]
We need to rethink how these sections are set out and then come back to this.

**Comment by tghosth** [comment]
This is what NIST says, I think the requirements are straightforward and they match what is in the draft of r4 of NIST
https://pages.nist.gov/800-63-4/sp800-63b.html#lookupver
https://pages.nist.gov/800-63-4/sp800-63b.html#out-of-band-verifiers

I therefore propose closing this with no further action.
