### ISSUE TITLE
new category - code review

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#1643]
We have some opened issues with requirement proposals which are not clearly input validation (but it's related).

The question is - where and with what name to create category for those

* https://github.com/OWASP/ASVS/issues/1600
* https://github.com/OWASP/ASVS/issues/1563
* https://github.com/OWASP/ASVS/issues/1562
* https://github.com/OWASP/ASVS/issues/1539

Currently labeled as "tmp code-review": https://github.com/OWASP/ASVS/labels/tmp%20code-review

**Comment by tghosth** [comment]
#### Sanitization

Honestly, I think the first 3 would all be considered "Sanitization"

* https://github.com/OWASP/ASVS/issues/1600 

    Add escape characters to regex

* https://github.com/OWASP/ASVS/issues/1563

    Sanitize input when dangerous objects are provided 

* https://github.com/OWASP/ASVS/issues/1562

    Sanitize input to avoid dangerous patterns are provided 

#### Other

This last one I think is a different 

* https://github.com/OWASP/ASVS/issues/1539

I would be inclined towards input validation because it is an input validation mechanism but they need to be performing the validation securely.


@elarlang, any other comments?

**Comment by elarlang** [comment]
If we consider "everything application uses is user input" we can fit everything to 5.* categories.

**Comment by tghosth** [comment]
Do you agree with my suggestion for the first 3?

(I am moving discussion on 4 [back to the dedicated issue](https://github.com/OWASP/ASVS/issues/1539#issuecomment-1627699876)).

**Comment by elarlang** [comment]
I can see that 3 first ones have found their place in other categories and the last one is closed. Anyway, as there is not enought content for this category at the moment, I close it now. We can recall the idea any time when we need it.
