### ISSUE TITLE
 4.2.2 does not seem like access control

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1652]
CSRF is also called "session riding" and is more of a session theft protection vs access control and should be moved

4.2.2 | [MODIFIED, MERGED FROM 13.2.3] Verify that the application defends against Cross-Site Request Forgery (CSRF) attacks to protect authenticated or sensitive public functionality using the development framework's built-in anti-CSRF functionality or CSRF tokens plus additional defense in depth measures. | ✓ | ✓ | ✓ | 352
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment]
"CSRF is not authorization issue" - this conclusion was made here: https://github.com/OWASP/ASVS/issues/795#issuecomment-743720732

And if the opened issue is just for wrong category, it's duplicate of https://github.com/OWASP/ASVS/issues/1352#issue-1352215924 + https://github.com/OWASP/ASVS/issues/1230

To call it session riding covers most of the issues with CSRF, but gives maybe wrong signal like CSRF is the issue only for autenticated users with active sessions. CSRF is also an issue also for not-authenticated users.

**Comment by tghosth** [comment]
I am going to drop this into the v3 rework bucket for now. I agree that access control seems like the wrong place but not sure I would consider it a client side control either.

**Comment by elarlang** [comment]
> ... not sure I would consider it a client side control either.

any arguments?

**Comment by jmanico** [comment]
I agree with you #jimAgreesWithElarOn Jul 16, 2023, at 10:45 PM, Elar Lang ***@***.***> wrote:

... not sure I would consider it a client side control either.

any arguments?

**Comment by elarlang** [comment]
> > > ... not sure I would consider it a client side control either.
> > 
> > 
> > any arguments?
> 
> For CSRF protection, the security mechanism is enforced at the server-side not the client side. Except for the samesite attribute.

Quite confusing statement. From that perspective we kind of don't have any client-side problems, as most of them you protect on the server side.

Without a browser (client) this attack does not exists. So it is from attack perspective.

**Comment by tghosth** [comment]
> Quite confusing statement. From that perspective we kind of don't have any client-side problems, as most of them you protect on the server side.

**Comment by elarlang** [comment]
> You could argue that from a tester perspective, this is a client side attack but from a developers perspective this is a server-side control.

What is the correct perspective for ASVS?

> Regular CSRF protection using tokens or whatever is implemented and enforced at the server. That is where the control exists.

Do you consider checking Origin header + checking correct request Content-Type header as a valid defense against CSRF (for API's)? If so, do you see it as "server-side" or as "client-side" mechanism?

**Comment by alamers** [comment]
> What is the correct perspective for ASVS?

Just a suggestion: from an end user perspective, it would be nice to be able to quickly decide if the control is applicanle at all. E.g., if I don’t have a front-end, should I care about this control?

**Comment by elarlang** [comment]
> > What is the correct perspective for ASVS?
> 
> Just a suggestion: from an end user perspective, it would be nice to be able to quickly decide if the control is applicanle at all. E.g., if I don’t have a front-end, should I care about this control?

... and this is my exact reason why I have proposed this to be included in "client-side" category (see https://github.com/OWASP/ASVS/issues/1230#issuecomment-1294517635 and https://github.com/OWASP/ASVS/issues/1230#issuecomment-1717182270).

**Comment by tghosth** [comment]
Yeah I think this goes into the client side category. Do we already have a label for that?

**Comment by tghosth** [comment]
Argh ok, I am going call in the WG

**Comment by tghosth** [comment]
![SignsBatmanGIF](https://github.com/OWASP/ASVS/assets/13623828/f6044c80-6233-4f97-b8cf-675c09eebd4b)

**Comment by elarlang** [comment]
More input here: https://github.com/OWASP/ASVS/issues/1230#issuecomment-1776736512

**Comment by csfreak92** [comment]
> > What is the correct perspective for ASVS?
> 
> Just a suggestion: from an end user perspective, it would be nice to be able to quickly decide if the control is applicanle at all. E.g., if I don’t have a front-end, should I care about this control?

@alamers, is the rationale for this suggestion for security testing web APIs that don't have front-end? Is this also why you would agree with it, @elarlang? I am trying to understand the main issue further so that I can provide some ideas/thoughts.

**Comment by csfreak92** [comment]
Can you expand a little more on this? I have been researching most of the day to find out examples of CSRF tagged vulnerabilities on public disclosure reports on bug bounty platforms to look for examples, yet they don't seem fitting with the examples you have. Maybe you could clarify further for the WG? 

> CSRF is also an issue also for not-authenticated users.

As the examples given, I am quite confused how example 1 is CSRF-related. Maybe you could help me understand? 

> Example 1 - let's force victim browser to make false authentication attempts. Victim does not have (business logical) session to the application. The result - most likely IP gets blocked, maybe user account gets locked etc.

I understand example 2 that in a public forum setting that could happen and may be an issue for anonymous user-forums. Or maybe I'm wrong? 

> Example 2 - non-authenticated users can leave some comments. Victim's browser is forced to enter some hate-speech or propaganda to some site. Done from victim browser and from victim IP.

Initially reading the comments above, I am inclined to agree with @tghosth as CSRF is more of a v3 Session Management-related vulnerability (which lightly touches on authorization somehow, but for the argument sake I would stick with v3 as well). I think having it as a general v3 requirement is better as the controls can be applied on both client-side and server-side whether in development or testing.

**Comment by elarlang** [comment]
> As the examples given, I am quite confused how example 1 is CSRF-related. Maybe you could help me understand?

Eem, well.
```
<script>
function poll() {
  fetch('https://APPLICATION.TLD/path/to/login', {
    method: 'post',
    mode: 'no-cors',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    },
    body: 'username=valid&password=not-valid'
  });
}
setInterval(poll, 100);
</script>
```

**Comment by elarlang** [comment]
> CSRF is also an issue also for not-authenticated users.

This was linked by Josh, but here: https://github.com/OWASP/ASVS/issues/795#issuecomment-828717449

**Comment by jmanico** [comment]
> CSRF is also an issue also for not-authenticated users.

Agreed. In the past I could use unauthenticed CSRF to force folks default Google language to Klingon or force items into folks shopping carts.

But is this really a ASVS worth risk? Unauthenticated functionality is rarely a real security issue.

**Comment by elarlang** [comment]
> But is this really a ASVS worth risk? Unauthenticated functionality is rarely a real security issue.

https://github.com/OWASP/ASVS/issues/1652#issuecomment-1778792816

For sure mostly CSRF are made and published against authenticated users with active sessions, but by concept is not session management problem (if we don't keeping a state as session).

**Comment by jmanico** [comment]
> > But is this really a ASVS worth risk? Unauthenticated functionality is rarely a real security issue.
> 
> [#1652 (comment)](https://github.com/OWASP/ASVS/issues/1652#issuecomment-1778792816)
> 
> For sure mostly CSRF are made and published against authenticated users with active sessions, but by concept is not session management problem (if we don't keeping a state as session).

This is absolutely a session-based problem. Even unauthenticated users have an anonymous session of some kind.

**Comment by csfreak92** [comment]
This is what I am trying to get into. I don't see it much of a risk or real security issue as well just like @jmanico said: 

> But is this really a ASVS worth risk? Unauthenticated functionality is rarely a real security issue.

Isn't this covered by rate-limiting controls? I can see the concern that it could be an issue with locking down an IP of a legitimate user, but that usually ends up in a helpdesk situation to deal with. I understand the merit for an unauthenticated form such as a "report violation" functionality which I abused one time on a pentest, which I constantly hit hundreds of times for that unauthenticated endpoint and caused hundreds of tickets in the company's incident response team to triage. However, I placed that under business logic issues/bugs which is in this case covered already in ASVS such as **11.1.5** 
 
> Constantly hitting authentication form via victim browser from **external site**. No session involved.

**Comment by elarlang** [comment]
In general, I don't mind to explain things - but here, it rising many questions.

Let's take this "authentication attempts CSRF" for the vulnerability - https://github.com/OWASP/ASVS/issues/1652#issuecomment-1778792816

If a random site in the Internet can force someones browser to make wrong authentication attempts and this way lock user out of his own account (especially nice when it's domain account somewhere in active directory). Also, "random site" can be public site and "site to authenticate" can be in internal network for the victim.

We can debate, is this "enough critical for ASVS" or not, but here the topic is - to which category CSRF belongs.

I take the previously vulnerable attack code, and make some fix.

Fix 1 - as request contains `Origin` header, the application on the server-side checks the `Origin` value to be in allow-list. Cross-Site part is taken down.

Where is the session here?

Fix 2 - let's use "double submit" pattern - an application sends one "csrf-token" cookie. With every request, there is extra HTTP header `x-csrf-cookie` (classical example) and it's value must match with cookie value.

Where is the session here?

**Comment by jmanico** [comment]
I stand corrected, this is a good reason to protect against 
unauthenticated CSRF.

**Comment by csfreak92** [comment]
Thanks for the explanation! This is really helpful now that you have painted that unauthenticated CSRF is also an issue (maybe we have to update in the OWASP definitions as well somewhere that this is an issue as just explained here, but that's another topic outside of this main issue). In that case, yes Fix 1 and 2 makes sense to mitigate it and I would agree as well, given you mentioned if a user's domain account got locked through this attack. 

I still don't know where CSRF should belong though. My best hunch at the moment is this is a session management-related issue.

**Comment by elarlang** [comment]
@csfreak92 - so you agree based on given examples that it is not session management problem, but still think that the best choice for that is session management?

I have provided examples, how it is not session management problem, I think it should be enough. If someone has opposite argument, then please - with practical experience on the topic where you argument and with examples to cover your arguments.

**Comment by csfreak92** [comment]
> 
> This is absolutely a session-based problem. Even unauthenticated users have an anonymous session of some kind.

Hi @elarlang, to quote @jmanico this is also my thought now regarding unauthenticated CSRF thanks to your clear and awesome examples fall into session management (even if it is an anonymous session handling). I think the one with rate limiting code example trying to lock the victim falls into this as well.

So, regarding the fixes you mentioned: 

> Fix 1 - as request contains `Origin` header, the application on the server-side checks the `Origin` value to be in allow-list. Cross-Site part is taken down.
> 
> Where is the session here?

Ok, in here yes there is no real session being handled whether authenticated or unauthenticated. This is a wrinkle and I understand why you don't see CSRF as under session management. I am struggling as well where to put CSRF now, but my best bet is under session management as most of the other cases of CSRF examples including the one below seems to fit there. 

> 
> Fix 2 - let's use "double submit" pattern - an application sends one "csrf-token" cookie. With every request, there is extra HTTP header `x-csrf-cookie` (classical example) and it's value must match with cookie value.
> 
> Where is the session here?

Here, the CSRF token somehow acts like an unauthenticated session (please do correct me if I am overthinking this, but that's the sort of understanding I have in this instance) as it is a way to determine that a certain HTTP request is from a certain "user". 

I do believe it is best choice to be placed under session management requirements. I cannot think of a good alternative unless the other folks have better ideas please?

**Comment by meghanjacquot** [comment]
Catching up on comments, it seems like this would be a good potential candidate for "V3.7 Defenses Against Session Management Exploits" based on both functions described as well as mitigations

**Comment by meghanjacquot** [comment]
Ok, so keeping with these fixes in mind, then if we're thinking not session management and not access control then is there a new category that should be created? 

> Fix 1 - as request contains `Origin` header, the application on the server-side checks the `Origin` value to be in allow-list. Cross-Site part is taken down.
> 
> Where is the session here?
> 
> Fix 2 - let's use "double submit" pattern - an application sends one "csrf-token" cookie. With every request, there is extra HTTP header `x-csrf-cookie` (classical example) and it's value must match with cookie value.

**Comment by elarlang** [comment]
for that proposal we have another monster-issue: https://github.com/OWASP/ASVS/issues/1230

TLDR: category "Attacks via browser" (not wording proposal) > section "Confused deputy"

**Comment by jmanico** [comment]
It is *mostly* a session management issue Elar, even if its not always 
session management. Is that fair?

**Comment by elarlang** [comment]
> It is *mostly* a session management issue Elar, even if its not always session management. Is that fair?

This is what I wrote in my fist response: https://github.com/OWASP/ASVS/issues/1652#issuecomment-1580244294

Yes, it is mostly **used against active sessions** because there it gives more impact for attacker.

By concept and technically it is not session management problem - you all agreed it is an issue against not-authenticated users. Why you still push it to session management...

Do we want to put XSSI (https://github.com/OWASP/ASVS/issues/903#issuecomment-1048862338) also to session management because it is mostly used against active sessions? (The answer is no,)

**Comment by elarlang** [comment]
For me it seems that some may live a bit in "yesterday", so few more pieces of information.

You can watch Cross-Site Request Forgery as "session riding" when a browser sends session information automatically with a (forged) request.

**Point 1** - when it is not sent automatically, nowadays - if session management is done with tokens and JavaScript need to put extra Authorization header into each request - it is not happening automatically by the browser.

This solution provides defense against CSRF attacks - you have a session, but you don't have CSRF.

**Point 2** - Session identifier is/was automatically sent via cookies, nowadays SameSite=Lax is default

Previously browsers sent automatically cookies with every request if those cookies just matched with the condition. Nowadays there is SameSite attribute for limiting that and most important here - [most browsers by default set it to Lax](https://caniuse.com/mdn-http_headers_set-cookie_samesite_lax_default). By this table, FireFox do not belong to this list, but FireFox has different cookie policy system, which also [blocks automatic cookie sending](https://blog.mozilla.org/en/security/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/).

It means - to have Cross-Site Request Forgery to be effective, you need to attack vector in Same-Site scope. Which makes "Cross-Site" part in the attack name quite... conflicting.

Other option to have CSRF vulnerability is when someone configures SameSite=None, but nowadays this one requires also Secure attribute to be set.

So it's fair to say - automatic CSRF which we know as "session riding" do not exist anymore with default configuration.


**Point 3** - authentication without session

If somewhere is Basic authentication used, then browser sends the authentication information as Authorization header with the request by default. We don't have session for the user, but we can force user browser to do requests. No session to ride.


**Point 4** - and now, when we don't have authenticated user or session.

Like proved here with attack scenario and Fix 1 and Fix 2, then the problem is actually more abstract and should be called "Client-Side Request Forgery" or "Browser Request Forgery" (Cross-Site in the name is mis-leading)

The point is - the defense must avoid accepting any forged request from 3rd party site via victim browser (which is not allowed to be by the application that way).

First and more known problem - if 3rd party site can force victim browser to make data operations as victim (previously given example - entering hate-speech or illegal content to some application).

Second - forcing victim browser to hit rate-limiting limits (or do whatever attacks), and there can be impact like locked user-account because of too many authentication attempts or just too many HTTP requests because of "Hotlinking". Basically we should talk about site-isolation here.

And maybe even worth separate requirement - origin of the request and anti-csrf must be checked before doing any action (like doing authentication or checking rate limits)

**Comment by tghosth** [comment]
I am happy to agree that this is not a session management problem.

I guess going back to basics, CSRF is basically spoofing because you are taking over another endpoint's identity. So maybe we need to move this to V2.

Either way, Elar I am comfortable to take the steer from you on where to put this but let's make a decision and move on as I don't want this to block us.

**Comment by elarlang** [comment]
> So maybe we need to move this to V2.

... I can probably write the same lengthy responses for this line. So at the moment I take direction to move it to "browser-side" and we just need to put descriptive chapter/section title there.

**Comment by jmanico** [comment]
Maybe we need a new category for CSRF since it does not fit will 
anywhere else.

Perhaps "General Web Security"

**Comment by elarlang** [comment]
Again new ideas, instead of following my proposal - without being able to say any opposite arguments.

First - V2 - it is for authentication. With CSRF attacker don't fake himself to the application to be someone else. The expected fix is not related with authentication. CSRF is problem also for non-authenticated users.

With tiny sarcasm, I can take recommendation from Jim and rename this so called "client-side" to "General Web Security" and everything is legit :)

So what is CSRF?

Problem for CSRF - an attacker can force victim browser to do request. The reason is not related to authentication, session or authorization. The outcome can be used against any category.

Expected defense against CSRF - an application must be sure, that the request was initiated from the same application (from the same Origin) and from the functionality which was intended to do so (i.e in same-origin situation you can not call resource demanding API request as image source from wysiwyg).

**Comment by jmanico** [comment]
Sa ei pea CSRF-i või ASVS-i pärast nutma, isegi kui me ei nõustu, kõik saab korda, Elar!

**Comment by tghosth** [comment]
Ok so looks like this is now relying on #1230

**Comment by elarlang** [comment]
The requirement is moved to the new "Web Frontend Security" category, as 50.3.1
