### ISSUE TITLE
Suggestion for Reconsideration of ASVS Requirement 8.3.1 Classification

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#1799]
I am writing to discuss the classification of requirement 8.3.1:

- Verify that sensitive data is only sent to the server in the HTTP message body or headers and that the URL and query string do not contain sensitive information, such as an API key or session token.

While the intent of this requirement is clear and aligns with best practices in information security, I believe its current classification as a Level 1 (L1) requirement may be overly stringent, especially considering common industry practices and practical implementation challenges.

A particular point of concern is the common industry practice of sending password reset links with codes embedded in the URL. They are pivotal to the security of the password reset process. The requirement, as stated, might lead to a misconception that such practices are non-compliant at the L1 level, potentially causing undue concern or leading organizations to adopt less user-friendly, though more compliant, practices.

**Comment by tghosth** [comment]
Wherever possible, URL based codes should be sent as "fragment" parameters (after the #) as these are not sent to the server but are still accessible via local JavaScript so that they can be processed. Maybe we just need to clarify this:


- Verify that sensitive data is only sent to the server in the HTTP message body or headers and that the URL and query string do not contain sensitive information, such as an API key or session token. Where sensitive data needs to be contained in a link such as a password reset token, this should be included as a "fragment" parameter after the # symbol so that it is not directly transmitted to the server.

**Comment by tghosth** [comment]
Ok but whenever possible doesn't appear in the requirement and I am not giving an option to do something in the query part of the URL in my proposed requirement so I am not sure what the problem is

**Comment by tghosth** [comment]
Having discussed with @elarlang, I think adding content about the fragment is overcomplicating things.

@ImanSharaf do you have a specific proposed change to the existing requirement?

**Comment by ImanSharaf** [comment]
We can close this.
