### ISSUE TITLE
Should easily visible logout functionality be a requirement or a recomendation

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1885]
In #870 this requirement from ASVS v3.0.1 was reinstated and currently [resides here](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x12-V3-Session-management.md#v38-session-termination):

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **3.8.4** | [ADDED] Verify that all pages that require authentication have easy and visible access to logout functionality. | ✓ | ✓ | ✓ | | |

Having gone through these requirements, I am thinking that this should actually be in the [recommendations section](https://github.com/OWASP/ASVS/blob/master/5.0/en/0x99-Appendix-X_Recommendations.md) since I don't think it explicitly makes the application less secure if the logout functionality is not visible, it is just a good idea to have it visible.

What do people think?

**Comment by jmanico** [comment]
I think that is totally fair, Josh. I'm happy to drop this issue.

**Comment by jmanico** [comment]
I'll add this to the recommendations section now.

**Comment by jmanico** [comment]
Please check out https://github.com/OWASP/ASVS/pull/1886

**Comment by elarlang** [comment]
It is a requirement - if an user can not see the log out link and needs to leave, then user just closes the browser window and leaves to session alive.

**Comment by elarlang** [comment]
Previously @jmanico changed is mind, maybe it's time to re-read the discussion: https://github.com/OWASP/ASVS/issues/870#issuecomment-768098766

**Comment by jmanico** [comment]
Hey, this is why idle session timeout exists. And yes, I change my mind sometimes.

**Comment by elarlang** [comment]
From a return on investment point of view, the logout link is probably one of the best security features. It does not take effort to implement but clearly provides value.

I recommend re-read the previous related issue (#870) and it's clear yes to me to keep this as a requirement.

**Comment by tghosth** [comment]
I read the issue, I think we need to do one of the following:

1) Weaken the requirement to remove "easy and visible access to" because practically speaking many apps require a couple of clicks to log out such as GitHub or Facebook.
2) Make the requirement level 3 as defense in depth.

**Comment by elarlang** [comment]
By principle, I don't agree that we need to change our requirements because just some apps are doing it differently. If there are reasonable arguments to do so, it's a different topic.

I consider GitHub and Facebook solutions to be easy and visible. I would keep it as it is. "easy" and "visible" both are arguable definitions, but without saying that, it's way harder to validate, "Is the logout functionality available on the page" or not.

It can be level 2, but no for only level 3.

But seriously, what is the problem with the requirement?

You point out "There is session idle" - well, session idle is a 2nd layer of defense - if the user left the workstation without closing the session (1st layer of defense). Your proposal is to let's remove 1st layer of defense and rely only on the 2nd layer. From this perspective, we can take it as a metaphor - we don't need to convert output correctly, let's just put CSP in place.

Session idle timeout does not help in the situation, when the session is taken over, logout helps.

**Comment by jmanico** [comment]
Elar, anytime I’m willing to change my mind back-and-forth over a requirement, it means I don’t have a solid opinion and those that do - like yourself - should take precedence over my opinions that waiver.

**Comment by csfreak92** [comment]
I agree with L2 as well. Although, I kind of feel that a visible logout link/button is one of those common sense controls developers should have in their applications (similar to it should have a login screen/page if there are accounts, etc) and I am leaning towards adding this just on the recommendations section to prevent ASVS from being bloated with too much controls that may not need to be explicitly called out. Just chiming in my idea.

**Comment by elarlang** [comment]
> I kind of feel that a visible logout link/button is one of those common sense controls developers should have in their applications...

This is an assumption and we know well, that assumption is the mother of all *** and security can not rely on assumptions. Common sense can be really different depending on your experience as a developer or as a security specialist.

**Comment by tghosth** [comment]
Ok, let's drop to L2 and then close this for now.

**Comment by tghosth** [comment]
Opened #1887

**Comment by elarlang** [comment]
Note: I accepted the level change and merged it, but now it feels not aligned with other similar requirements. But there is no point in discussing levels before levels are not defined yet :)
