### ISSUE TITLE
Section titles in V12

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2066]
Spin-off from https://github.com/OWASP/ASVS/issues/1390#issuecomment-2330879357

Some section titles are from end-user perspective, but ASVS should be written from the application perspective

* File upload - the application does not upload the file, but accepting it
* File download - the application does not download the file, but serving it

There is another topic to be opened in the future for the "File execution" title, but let the related requirements fall to place first.

**Comment by jmanico** [comment]
The problem is that these requirements often fit into both catagories. So unless you want duplication I do not think this is possible.

For example, untrusted filenames driving file upload or download from user files can cause problems.

For example, filenames on download:

![image](https://github.com/user-attachments/assets/051ce033-a32b-44c8-b084-44c0e88d6d5a)

Or filenames on upload:

![image](https://github.com/user-attachments/assets/9bedaaa6-c2c1-419e-94cb-ee4a5b983bf7)

**Comment by elarlang** [comment]
Given examples are both "using untrusted input for file operation" problem and it is topic for issue https://github.com/OWASP/ASVS/issues/1427

If you look into the mentioned sections, then it clear file serving or accepting files issues. Path traversal etc topics are currently in "File execution".

**Comment by jmanico** [comment]
Fair enough. Looking over these requirements in v12 I am certain we can have a file upload and download section. That's a fair ask @elarlang and I'll think about it some and get back to you.

**Comment by tghosth** [comment]
Whilst I understand the concept of talking from the application's perspective I think having a section for "how the application provides file upload functionality" and "how the application provides file download functionality" is still understandable by all users of ASVS. I would prefer to leave the titles as they are.
