### ISSUE TITLE
V20.7 is too broad/vague

### ISSUE THREAD

**Issue by ordinaehs** [OWASP/ASVS#209]
I find V20.7 as it is formulated currently quite broad and/or vague. "Verify that the device prevents leaking of sensitive information." This could encompass almost anything. I assume it was written with specific leakages in mind; can it be reformulated to be more specific?

Edit: I suspect this is based on V17.5? However, V17.5 does mention specific examples which better define the scope of what is meant.

**Comment by vanderaj** [comment]
We might have to refer this back to the original author; I think we need to really go through the IoT threat model to understand what's really happening. What happens if an open BIOS and open sourced hardware IoT platform gets going, and they need to comply with this. I'm not sure we are hitting the right nail here.

**Comment by jmanico** [comment]
I'm tempted to just drop this, it's vague.

**Comment by jmanico** [comment]
This is closed out per de759acfa423fe3c2e5f7d96bcd857fe8f707cd3
