### ISSUE TITLE
clarification for V4.1 and V4.2

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#2139]
In V4 we have sections:
* V4.1 General Access Control Design
* V4.2 Operation Level Access Control

Can we have clear ruleset, why those are separate and by what conditions one requirement belong to them. For example, why 4.1.3 is in V4.1 not in V4.2 although it's pretty much same requirement as 4.2.1.

**Comment by elarlang** [comment]
ping @tghosth

**Comment by EnigmaRosa** [comment]
From my understanding, V4.1 is more focused on design/architecture of the access control system and V4.2 on some of the implementation details. Is that correct?

**Comment by tghosth** [comment]
Not sure we have ever had any guidance there so I am open to suggestions. I think it would be good to have some brief text at the start of each section which explains what sort of requirements are going in there.

**Comment by EnigmaRosa** [comment]
Some guidance would be great - I think that means we have to do that throughout the entire standard. 
Before we write guidance though, we should agree on the rule set for 4.1 and 4.2 though.

**Comment by elarlang** [comment]
> Some guidance would be great - I think that means we have to do that throughout the entire standard.

Yes, and for that we have a separate issue opened so we don't need to discuss it here: https://github.com/OWASP/ASVS/issues/1797

> we should agree on the rule set for 4.1 and 4.2 though.

If we it is not easy to find what is the difference between those section, it is natural to ask, do we need 2 separate chapters.

If we use architecture/principle for V4.1 and implementation for V4.2

* V4.1.1 - arhitecture/principle
* V4.1.2 - implementation
* V4.1.3 - implementation (although can be watched also as a principle)
* V4.1.5 - arhitecture/principle
* V4.2.1 - implementation (pretty much the same as V4.1.3)
* V4.2.3 - implementation (duplicate of V4.1.3 + V4.2.3)
* V4.2.4 - implementation

**Comment by elarlang** [comment]
Linking it here: https://github.com/OWASP/ASVS/issues/2063#issuecomment-2431653476

**Comment by EnigmaRosa** [comment]
Sure, I can get behind that

**Comment by EnigmaRosa** [comment]
Also, may I please be assigned this issue? It makes it easier for me to track

**Comment by elarlang** [comment]
I assigned, but it is easier to track based on label: https://github.com/OWASP/ASVS/labels/V4

**Comment by EnigmaRosa** [comment]
Given this split, should we re-organize the requirements?

**Comment by tghosth** [comment]
I think we will move these around next week when we finalize the requirements during the summit.

**Comment by jmanico** [comment]
I want to see the split requirments from the POLP split to be at the top (4.1.1, 4.1.2, 4.1.3) and rename 4.1 to be "Core Access Control Requirements" and put the other requirements like client slide design in section 4.2

**Comment by jmanico** [comment]
Here is my suggestion to fully reorg v4

# V4 Access Control

## Control Objective

Authorization is the concept of allowing access to resources only to those permitted to use them. Ensure that a verified application satisfies the following high-level requirements:

* Document access control rules, including decision-making factors and environmental contexts.
* Users access only permitted access based on defined entitlements.
* Access decisions consider real-time contextual attributes (e.g., location, device).
* Restrict data and field access by explicit permissions to prevent unauthorized access (IDOR, BOLA, BOPLA).
* Prevent cross-tenant access in multi-tenant applications, with access based on user, not intermediary, permissions.
* Protect access control metadata from tampering or replay.

Due to complexity, manual or assisted testing is recommended, with automated end-to-end tests in the CI/CD pipeline for continuous validation.

## V4.1 Access Control Documentation

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **1.4.6** | [ADDED] Verify that the application documentation defines controls which use changes to a user's regular environmental and contextual attributes (such as time of day, location, IP address, or device) to make security decisions, including those pertaining to authentication and authorization. These changes should be detected both when the user tries to start a new session and also in the course of an existing session. | | | ✓ | |
| **1.4.7** | [ADDED] Verify that access control documentation defines the rules for access control decision-making, specifying user and subject attributes, resource attributes, and relevant environmental factors involved in the process. | ✓ | ✓ | ✓ | |

## V4.2 General Access Control Design

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.3** | [MODIFIED] Verify that the application ensures that function level access is restricted to consumers 
| **4.2.1** | [MODIFIED] Verify that the application ensures that data specific access is restricted to consumers with explicit permissions to specific data items to mitigate insecure direct object reference (IDOR) and broken object level authorization (BOLA). | ✓ | ✓ | ✓ | 639 |
| **4.2.3** | [ADDED] Verify that the application ensures that field level access is restricted to consumers with explicit permissions to specific fields to mitigate broken object property level authorization (BOPLA). | | ✓ | ✓ | 283 |

## V4.3 Other Access Control Considerations

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **4.1.1** | [MODIFIED] Verify that the application enforces access control rules at a trusted service layer and doesn't rely on controls which an untrusted user could manipulate such as client-side JavaScript. | ✓ | ✓ | ✓ | 602 |
| **4.1.5** | [GRAMMAR] Verify that access controls fail securely by denying access, including when an exception occurs. | ✓ | ✓ | ✓ | 285 |
| **4.1.6** | [ADDED] Verify that changes to values on which access control decisions are made, are applied immediately. Where changes cannot be applied immediately, (such as when relying on data in cryptographically secured tokens), there must be mitigating controls to alert when a user performs an action when they should no longer be able to do so, and revert the change. Note that this would be unable to mitigate information leakage. | | ✓ | ✓ | |
| **4.3.1** | [MODIFIED, LEVEL L1 > L3] Verify that access to administrative interfaces incorporates multiple layers of security, including continuous user identity verification, device security posture assessment, and contextual risk analysis, ensuring that network location or trusted endpoints are not the sole factors for authorization even though they reduce likelihood. | | | ✓ | 419 |
| **4.2.4** | [ADDED] Verify that multi-tenant applications use cross-tenant controls to ensure user operations will never affect tenants with which they do not have permissions to interact. | ✓ | ✓ | ✓ | 283 |
| **4.2.5** | [ADDED] Verify that access to an object is based on the originating subject's (e.g. user's) permissions, not on the permissions of any intermediary or service acting on their behalf. For example, if a user calls a web service using a signed token for authentication, and the service then requests data from a different service, the second service should use the user's signed token, rather than a machine-to-machine token from the first service, to make permission decisions. | | | ✓ | 441 |

## References

For more information, see also:

* [OWASP Testing Guide 4.0: Authorization](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/05-Authorization_Testing/README.html)
* [OWASP Cheat Sheet: Access Control](https://cheatsheetseries.owasp.org/cheatsheets/Access_Control_Cheat_Sheet.html)

**Comment by jmanico** [comment]
I am so freaking thrilled to finally close out the last of the access control issues :)
