### ISSUE TITLE
Challenge to ASVS Item 10.2.3: Scope and Consistency Concerns

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2145]
Current Item Text

10.2.3: "Verify that the application source code and third party libraries do not contain back doors, such as hard-coded or additional undocumented accounts or keys, code obfuscation, undocumented binary blobs, rootkits, or anti-debugging, insecure debugging features, or otherwise out of date, insecure, or hidden functionality that could be used maliciously if discovered."

Scope Inconsistency: Desktop vs. Web Applications

- Reference: [ASVS Issue #803](https://github.com/OWASP/ASVS/issues/803)
- Concern: ASVS is presumed not to cover desktop applications, yet item 10.2.3 mentions rootkits, which are typically associated with desktop/system-level malware.
- Question: Should references to system-level threats like rootkits be removed to maintain consistency with ASVS's web application focus?

Also, I believe based on the same logic we should remove 14.1.2, as C and C++ are not common languages for web app development.  

Furthermore, **I believe the final production-ready artifact for any web app should be obfuscated and protected against reverse engineering.**

**Comment by elarlang** [comment]
related: #1468

**Comment by ImanSharaf** [comment]
Security through obscurity: While not a complete security solution, obfuscation can add an extra layer of difficulty for potential attackers trying to understand the code.

**Comment by ImanSharaf** [comment]
@elarlang what about removing 14.1.2?

**Comment by elarlang** [comment]
So, let's take this requirement to pieces.

* Verify that the
  * application source code
  * and third party
    * libraries do not contain back doors

It means one must access the source code for 3rd party library - is it always the case for big frameworks?

* , such as 
  * hard-coded or additional undocumented accounts or keys - okeish
  * code obfuscation - ok, but it feels like some oldschool-php-era thing. how it is valid for compiled java application?
  * undocumented binary blobs - and if it is documented, you still can not see, what is inside.
  * rootkits - the issue was focused on that keyword, it should not stay here. Or maybe some just meant web shell?
  * or anti-debugging - why you should have debugging in procution?
  * insecure debugging features - how to verify that some debugging feature is insecure? why debugging is allowed at all in production? (covered by 14.3.2)
  * or otherwise out of date (covered by 14.2.1)
  * insecure - meh
  * or hidden functionality - need to be defined, every hidden functionality is not a security risk. Can also say it is covered by 14.1.6
 that could be used maliciously if discovered.

I can see 2 points in this requirement:
* you need to fully control your source code, including 3rd party libraries
* you need to be sure, that there is no hard-coded/undocumented access built in

My validation questions are:
* is this requirement anyhow realistic?

**Comment by jmanico** [comment]
I do see some large organizations review third party code for backdoors, but this is (at best) a L3 requirement. Since it's so unrealistic for most organizations, I can see why we want to drop it.

**Comment by elarlang** [comment]
Jim, it is L3 requirement also at the moment.

CWE points to CWE-507: Trojan Horse

Before droping something, there should be clear understanding, that we have all important points covered somewhere and somehow.

For me, current requirement can be shortened to:
> Verify that the application source code and third party libraries do not contain back doors, such as hard-coded or additional undocumented accounts or keys, code obfuscation, undocumented binary blobs.

Further action from here - do we want to split it to "harcoded credentials" and "functional backdoor" requirements?

We kind of have duplicate for backdoor also (at least) in 10.2.1 and 10.2.6.

As I have seen "developer's features" for themselves, I can say that the requirement in a way is valid.

**Comment by ImanSharaf** [comment]
I like your suggestion @elarlang. Also, I am in favour of merging 10.2.4, 10.2.5, 10.2.3 and 10.2.6 and as you mentioned in #1468 we need to remove "third party libraries".

**Comment by ImanSharaf** [comment]
I propose this one (after merging 10.2.3, 10.2.4, 10.2.5, and 10.2.6)

Verify that the application source code is free from backdoors, malicious code (e.g., salami attacks, logic bombs, time bombs), undocumented or hidden features (e.g., Easter eggs, insecure debugging tools)

**Comment by jmanico** [comment]
I suggest we cleanup like so : or even kill the requirement.

"Ensure the application's source code is free from backdoors, malicious code (e.g., salami attacks, logic bombs, time bombs), and hidden Easter eggs."

**Comment by tghosth** [comment]
We had a discussion at the summit including Elar, Jim, Eden, Ryan, Iman and myself.

Consensus was to remove the requirements related to "malicious code" and move to the recommendations section (well that part was mostly me)

@ImanSharaf to open PR
