### ISSUE TITLE
Proposal to Merge Sections 13.2 and 13.3, and Update JSON Schema Validation in 13.2.2

### ISSUE THREAD

**Issue by ImanSharaf** [OWASP/ASVS#2260]
I'd like to propose a refinement to the current structure of sections 13.2 and 13.3 in the API Security section of the ASVS. Given the limited content in 13.3, merging it with 13.2 may provide a more streamlined presentation of API schema validation practices.

Specifically:
1. **Merge 13.2 (RESTful Web Service) and 13.3 (SOAP Web Service)**: Since both sections focus on schema validation and content-type verification, combining these will unify guidance on REST and SOAP services, enhancing clarity.
2. **Update 13.2.2 to encompass both XML and JSON**: I suggest revising the line as follows:
   - **Current**: "[LEVEL L1 > L3] Verify that JSON schema validation is in place and verified before accepting input."
   - **Suggested**: "[LEVEL L1 > L3] Verify that both JSON and XML schema validation are in place and verified before accepting input."

## V13.2 Web Service

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.2.2** | [LEVEL L1 > L3] Verify that both JSON and XML schema validation are in place and verified before accepting input. | | | ✓ | 20 |
| **13.2.5** | Verify that REST services explicitly check the incoming Content-Type to be the expected one, such as application/xml or application/json. | | ✓ | ✓ | 436 |

**Comment by tghosth** [comment]
Suggested update, note the change to [13.2.5](https://github.com/OWASP/ASVS/blob/ef0e0f5940398f225a1ddb5dd0f957ab43137979/5.0/en/0x21-V13-API.md#v132-restful-web-service)

---

## V13.2 **Web Services**

As at this time, there is a "published version" of the JSON schema validation specification, which is considered production ready. However, there is not yet a version which is considered strictly "stable". As such, when considering using JSON schema validation, be sure to also apply the standard input validation guidance from Chapter 5 of ASVS.

Due to the lack of a formal stable version of the JSON schema validation specification, carefully monitor any JSON schema validation libraries in use, as they may need to be updated once the standard is formalized and bugs are ironed out of reference implementations.

Note: Due to issues with XXE attacks against DTDs, DTD validation should not be used, and framework DTD evaluation disabled as per the requirements set out in chapter V5.

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.2.1** | [MOVED TO 13.6.2] | | | | |
| **13.2.2** | [MODIFIED, MERGED FROM 13.3.1, LEVEL L1 > L3] Verify that JSON or XSD schema validation is in place to that objects received are properly formed, followed by validation of each input field before any processing of that data takes place. | | | ✓ | 20 |
| **13.2.3** | [DELETED, MERGED TO 50.3.1] | | | | |
| **13.2.4** | [DELETED, DUPLICATE OF 11.1.4] | | | | |
| **13.2.5** | [MODIFIED] Verify that web services explicitly check the incoming Content-Type to be the expected one, such as application/xml or application/json. | | ✓ | ✓ | 436 |
| **13.2.6** | [MOVED TO 13.1.6] | | | | |

## V13.3 SOAP Web Service

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.3.1** | [DELETED, MERGED TO 13.2.2] | | | | |
| **13.3.2** | [DELETED, DUPLICATE OF 13.2.6] | | | | |

---

@jmanico @elarlang @danielcuthbert @cronchie @ryarmst @TobiasAhnoff @randomstuff

What do we think?

**Comment by randomstuff** [comment]
> [MODIFIED] Verify that web services explicitly check the incoming Content-Type to be the expected one, such as application/xml or application/json.

:+1:

**Comment by elarlang** [comment]
Is 13.2.5 a problem without browser is involved? I can see it as a requirement to trigger pre-flight request for cross-origin requests. Maybe it's a V50 content.

> Verify that web services explicitly check the value of the HTTP request 'Content-Type' header field to be the expected one, such as application/xml or application/json.

**Comment by tghosth** [comment]
> > Verify that web services explicitly check the value of the HTTP request 'Content-Type' header field to be the expected one, such as application/xml or application/json.
>
> Is 13.2.5 a problem without browser is involved? I can see it as a requirement to trigger pre-flight request for cross-origin requests. Maybe it's a V50 content.

Yes because this is a request header so even a non browser client will send it and it will control how the server processes the request content

> I would claim that [JSON schema](https://json-schema.org/) or XML schema validation (XSD and friends) are not necessarily required for the application to be secure. Some form of input validation must be there but it might take a lot of forms.

@elarlang @ImanSharaf what do you think about this?

**Comment by tghosth** [comment]
> I would claim that [JSON schema](https://json-schema.org/) or XML schema validation (XSD and friends) are not necessarily required for the application to be secure. Some form of input validation must be there but it might take a lot of forms.

@ryarmst what do you think about this?

**Comment by ryarmst** [comment]
First, I agree that this has relevance outside the browser:

> Verify that web services explicitly check the value of the HTTP request 'Content-Type' header field to be the expected one, such as application/xml or application/json.

Agree with @randomstuff that schema validation is not necessary, but in practice it would prevent issues I have seen. Perhaps it is another that falls into the defense in depth category (not necessary for security, but nevertheless helpful for reducing risk). I think it is appropriate at L3 (I have almost never seen implemented). I would also be happy to generalize it to other forms of "structured" data (data interchange formats?), but perhaps this is unnecessary: 

> Verify that structured data objects are validated to ensure they are properly formed before processing the data contained within individual input fields. This requires implementing schema validation for formats like JSON and XML. 

I will also note that this is somewhat related to 5.5.5 as in #2297. @cronchie

**Comment by jmanico** [comment]
+1 Josh

**Comment by tghosth** [comment]
Ok so maybe as a modification proposal:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.2.2** | [MODIFIED, MERGED FROM 13.3.1, LEVEL L1 > L3] Verify that structured data objects are validated to ensure they are properly formed, followed by validation of each input field before any processing of that data takes place. This could involve implementing schema validation for formats like JSON and XML. | | | ✓ | 20 |

**Comment by tghosth** [comment]
@randomstuff @elarlang @ryarmst @jmanico

**Comment by cronchie** [comment]
@tghosth I like your phrasing, but propose adding L2 to the requirement. As you noted, it ain't so difficult to use a framework for input validation, and JSON schemas have been supported for a while now, so I would expect any moderately mature app to be validating all its inputs in this manner.

**Comment by tghosth** [comment]
> @tghosth I like your phrasing, but propose adding L2 to the requirement. As you noted, it ain't so difficult to use a framework for input validation, and JSON schemas have been supported for a while now, so I would expect any moderately mature app to be validating all its inputs in this manner.

I think we have other input validation controls and validating using schemas is particularly hard to do, plus L2 is going to be very big so I am pretty solid on L3 here.
