### ISSUE TITLE
session management in general: should we write something about CORS?

### ISSUE THREAD

**Issue by tjherzog** [OWASP/ASVS#239]
We had an interesting talk on CORS at the last OWASP Day in Germany. There seem to be quite some things in CORS which could go wrong if you don't use CORS carefully. What do you think?
On https://web-in-security.blogspot.de/2017/07/cors-misconfigurations-on-large-scale.html you can find more details.

**Comment by TheDauntless** [comment]
I was just looking through 3.1, expecting the CORS header to be part of "V18: Web services verification requirements", as that is typically where we see issues with this.

Right now, CORS is nowhere in there, and putting CORS: * is definitely a big security risk, which, I think, isn't mentioned anywhere right now.

In my opinion, V18 is the best place for this.

**Comment by vanderaj** [comment]
@jmanico - please check out the revised V11.

**Comment by vanderaj** [comment]
If it's not just about ACAO, please, consider updating the new one or writing one or more. 

I'm torn on V11 vs V18. It's a configuration item, but it's also access control, in particular API access control, but even basic React / Angular apps use it, and folks might not consider their app to be an API. @tjherzog @TheDauntless @jmanico thoughts?

**Comment by TheDauntless** [comment]
If you reed the descriptions of both chapters, it falls under neither... It's not a web service according to the description (which might also be too narrow), and it's not an insecure basic config (you have to explicitly make it dangerous)

Maybe we should put it under V4: Access Control. This is also where CSRF is described, which is kind of a similar issue ("execute" instead of "read"). Additionally, if you're testing a web service, you will hopefully also verify V4.

**Comment by aabashkin** [comment]
Access Control seems natural to me

**Comment by jmanico** [comment]
I am ok with V4 access control or V18 for web config. It's a really big and important topic.

**Comment by tghosth** [comment]
CORS is now referenced in [19.4.10](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x24-V19-Config.md#194-http-configuration) and [16.5](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x21-V16-Files-Resources.md#security-verification-requirements) so I think this can now be closed.
