### ISSUE TITLE
Terminology and glossary update for token clarity

### ISSUE THREAD

**Issue by ryarmst** [OWASP/ASVS#2414]
Following from #2384, here is an initial proposal for some changes:

### New Terms

**Self-Contained Token** - A token that encapsulates one or more attributes that do not rely on server-side state or other external storage. These tokens ensure the authenticity and integrity of their contained attributes, enabling secure, "stateless" information exchange across systems.

@randomstuff Should we define **Reference Token**?

### Updated

**Cryptographically Secured Token** -  A token protected using cryptographic techniques, such as digital signatures or message authentication codes (MACs), to ensure the authenticity and integrity of its data. These tokens can range from simple signed identifiers to more complex formats like JSON Web Tokens (JWTs).

**Comment by ryarmst** [comment]
How about the following:

**Cryptographically Secured Token** -  A token protected using cryptographic techniques, such as digital signatures or message authentication codes (MACs), to ensure the authenticity and integrity of its data. These tokens can range from simple signed identifiers to more complex formats like JSON Web Tokens (JWTs).

**Reference Token** - A type of token that acts as a pointer or identifier to state or metadata stored on a server. Unlike self-contained tokens, which embed some of their relevant data within the token itself, reference tokens contain no intrinsic information, instead relying on the server for context. They may be simple random identifiers or cryptographically secured tokens.

**Self-Contained Token** - A token that encapsulates one or more attributes that do not rely on server-side state or other external storage. These tokens ensure the authenticity and integrity of their contained attributes, enabling secure, "stateless" information exchange across systems. Self-contained tokens are a subset of cryptographically secured tokens, and include SAML and JWTs.

**Comment by randomstuff** [comment]
> Cryptographically Secured Token […] to ensure the authenticity and integrity of its data

Do we need to say that it *might* be encrypted as well (in order to provide confidentiality)? Or should we actually call it a "cryptographically authenticated token"?

> Reference Token […] They may be simple random identifiers or cryptographically secured tokens.

Does storing secure_random_id in database and using secure_hash(secure_random_id) count as as "cryptographically secured tokens"? (This might be important wrt the formulation of the requirements.)

**Comment by elarlang** [comment]
Some more ideas.

> Do we need to say that it might be encrypted as well (in order to provide confidentiality)? Or should we actually call it a "cryptographically authenticated token"?

I think we should, it gives the same effect (provides integrity) but additionally provides confidentiality. It may be useful when someone decides to use sensitive data in those tokens.

> Reference Token - A type of token that acts as a pointer or identifier to state or metadata stored on a server. 

Is this part actually enough?

If you re-call your own written hybrid scenarios to describe why "stateless" is bad, then reference token may contain some data, but by concept it is also reference token. It just have self-contained token inside.

**Comment by randomstuff** [comment]
> reference token may contain some data, but by concept it is also reference token. It just have self-contained token inside.

I would have said it the other way around. I would add a in "self-contained token" : "In practice, the token may not be completely self-contained and contain some reference for context to be lookup-ed up in the server."

**Comment by elarlang** [comment]
The value is exactly there - those are not the same, and if we define them, it is helpful clarification. Taking into account how many discussions we have had on the topic, I prefer it to be written down as proposed at the moment.

But we need to recheck all the requirements using those terms...

**Comment by tghosth** [comment]
I think part of the reason that we have spent so long discussing them is that they differences aren't that large, and at that point I am not convinced they are that important...

**Comment by elarlang** [comment]
I really don't want to have this discussion from the beginning.

**Comment by tghosth** [comment]
We can discuss but I have followed this discussion all the way through and unfortunately at no point has the practical difference been clear to me. From my perspective, a self-contained token can only be useful if it has it's integrity guaranteed through some cryptographic method. I still don't see anything which would  justify tying ourselves in knots over terminology

**Comment by tghosth** [comment]
So @ryarmst if we assume we keep all 3 definitions, do the definitions match how we currently use these terms in requirements?

**Comment by elarlang** [comment]
Self-contained tokens are using crypto to provide integrity and can be also for confidentiality.  If a requirement points to "token content", it can use the term "self-contained token".

Compared to "self-contained tokens", the "Cryptographically secured tokens" is wider and independent term. If a requirement points to "token integrity", it can use the term "Cryptographically secured tokens".

---

* In section "V52.1 Token source and integrity" we can use "cryptographically secured tokens" because this section is handling the crypto part
* In section "V52.2 Using token content" we use "self-contained token" - those requirements are dealing with the token content

---

Pointing out some more examples, probably worth opening a separate issue if the terminology is in place.

Those are not proposals and no need to discuss here, I just point them out to have the feeling of the terminology usage.

* V3.1.3 Verify that the application uses either ~~cryptographically secured or random session tokens~~ for session management. Static API secrets and keys should be avoided.
  * V3.1.3 Verify that the application uses either **self-contaned tokens or reference tokens** for session management. Static API secrets and keys should be avoided.

* V4.2.4 Verify that changes to values on which access control decisions are made are applied immediately. Where changes cannot be applied immediately, (such as when relying on data in ~~cryptographically secured tokens~~), there must be mitigating controls to alert when a consumer performs an action when they should no longer be able to do so and revert the change. Note that this would be unable to mitigate information leakage.
  * V4.2.4 Verify that changes to values on which access control decisions are made are applied immediately. Where changes cannot be applied immediately, (such as when relying on data in **self-contained tokens**), there must be mitigating controls to alert when a consumer performs an action when they should no longer be able to do so and revert the change. Note that this would be unable to mitigate information leakage.

* V4.2.5 [ADDED] Verify that access to an object is based on the originating subject's (e.g. consumer's) permissions, not on the permissions of any intermediary or service acting on their behalf. For example, if a consumer calls a web service using a signed token for authentication, and the service then requests data from a different service, the second service should use the consumer's signed token, rather than a machine-to-machine token from the first service, to make permission decisions.
  * Signed token?

**Comment by tghosth** [comment]
Can someone give me an example of a "Cryptographically Secured Token" which would not be a "Self-Contained token"?

**Comment by randomstuff** [comment]
I think that would be `reference_id + "." + mac(reference_id, key`).

**Comment by tghosth** [comment]
> I feel we are looping with this one and PR is different than agreed in the related issue.
> 
> * "Self-Contained Token - A subset of cryptographically secured tokens" - I really don't like that. It's not a subset, self-contained tokens are using cryptography for integrity. Whatever uses crypto for integrity is not subset of it, those are just using it. I think those proposals were good: [Terminology and glossary update for token clarity #2414 (comment)](https://github.com/OWASP/ASVS/issues/2414#issuecomment-2506815656)

@elarlang the definition for self-contained tokens [in the comment you just pointed to](https://github.com/OWASP/ASVS/issues/2414#issuecomment-2506815656) says "_Self-contained tokens are a subset of cryptographically secured tokens_"

I am open to alternative wording but I don't think the definition changes I made materially change what is in that comment above.

> * I prefer V52 title to be "Self-contained tokens" as it was.

I don't understand how we do that if we are assuming that non self-contained tokens like @randomstuff [gave an example of above](https://github.com/OWASP/ASVS/issues/2414#issuecomment-2519475797) are also in scope for this chapter.

> * V4.2.5 should use self-contained tokens

Disagree, this could also be an example where a non self-contained tokens like @randomstuff [gave an example of above](https://github.com/OWASP/ASVS/issues/2414#issuecomment-2519475797) is used.

**Comment by elarlang** [comment]
> self-contained tokens are a subset of cryptographically secured tokens

Missed that part. I don't like that definition.

Back to the step 1.

At least now you got what I meant (in #2384) by "conflict was created into the chapter, as cryptographically secured token" is wider, than "self-contained tokens" and the focus for the section / chapter is self-contained tokens?

Crypto-oriented chapter belongs to V6.

**Comment by elarlang** [comment]
Notes about the main focus and title for V52, "self-contained" vs "cryptographically secured"

https://github.com/OWASP/ASVS/issues/2384#issuecomment-2493363526

> If it creates a gap or not covered area, it should be considered to have a separate more general requirement into V6 to cover that - as we have more general requirement in current V3.5 to have abstract requirements and specific requirements in the OAuth section to cover the special need.

https://github.com/OWASP/ASVS/issues/2384#issuecomment-2498695519

> As it is corner-stone for API security, I prefer to have specific requirements for self-contained tokens. At the same time, if those are not specific to self-contained tokens and can easily applied to whatever, we need to recheck the duplication part and the structure.

**Comment by tghosth** [comment]
I had a long discussion with Elar about this. We feel like the key functional point here is the concept of the "self-contained" token. Self-contained token is also the more widely recognised term in the industry and how we would like to characterise the chapter (V52).

Self-contained tokens will almost certainly need to be cryptographically secured. We feel trying to use and define both terms simultaneously will make for more confusing requirements and would prefer to stick with one of them. This does leave a small gap for the use case of a cryptographically secured token which is not self-contained, but we feel that this is very niche and we don't want to sacrifice clarity for it.

I updated #2434 accordingly
