### ISSUE TITLE
8.2 Verify that error handling logic in security controls  denies access by default

### ISSUE THREAD

**Issue by smjogi** [OWASP/ASVS#250]
I do not understand this question. Could someone explain / expand?

**Comment by vanderaj** [comment]
Say if you throw an exception whilst authenticating, and you start out with some code that does this:

`
profile.authenticated = true
profile.role = admin


user = model.findUserByName(req.username)
try {
if ( user.password == hash(req.password) ) {
 // do something
} 
catch (Exception ex)
{
  Show an error
}
}`

The problem is that by default, that badly written pseudo-code if it errors out for *ANY* reason will leave the user logged in and an admin. 

Does that help? Do we need to improve the references or add a testing guide link?

**Comment by vanderaj** [comment]
I'm going to close this as it's a dupe of #192. If you want to discuss further, feel free to re-open.
