### ISSUE TITLE
Guidance for Certifying Organizations - may need 2 accounts for testing horizontal priv esc?

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#542]
The first paragraph talks about the need for "access to test systems (including access to at least one account in each role),", however I think it might be fair to say that 2 accounts would be needed for testing horizontal privilege escalation between users of the same role - several ASVS requirements indicates that such tests should be done, e.g., testing that a user only can create/update data for their own profile and not for other users (unless explicitly authorized to do so)

**Comment by mastacheata** [comment]
That depends highly on the application design.
Take for example a marketplace like ebay: You log in as user A for which you have the credentials and then somehow manage to create an offer in the name of account B. Do you really need access to account B in order to verify that there's something afoul?

If full access to the escalated account was neccessary, the attacker would need to gain that same level of access through the problem.

**Comment by tghosth** [comment]
Addressed with https://github.com/OWASP/ASVS/commit/f392872f4fb8808f83decfd61782c476f9aef966
