### ISSUE TITLE
V3.1.1 - Remove "as GET parameters"

### ISSUE THREAD

**Issue by securitybits** [OWASP/ASVS#552]
"Verify the application never reveals session tokens **as GET parameters** in URLs or error messages." - no point to limit this to GET requests, same issue applies to POST and other verbs too - in short the URL should not contain the session id (regardless of HTTP verb or whether as query parameter or path parameter)

**Comment by mastacheata** [comment]
I doubt this was intended to mean only GET requests. It's more of a colloquialism for query params to just call them GET params. (Especially in PHP, where query params are available in the $_GET superglobal, regardless of the HTTP verb)
You are right, though: This should be reworded to say query parameters instead of using an ambiguous colloquialism, I guess.

**Comment by tghosth** [comment]
@securitybits @mastacheata how about now: https://github.com/OWASP/ASVS/commit/943a58ca5e7bb38b467ba50daa4251c4f51bdd2b?

**Comment by mastacheata** [comment]
LGTM, thanks.
