### ISSUE TITLE
V2: NIST 800-63 considers [..] SMS [..] notifications as insecure

### ISSUE THREAD

**Issue by pich4ya** [OWASP/ASVS#559]
Refer to ASVS Draft 4.0, "NIST 800-63 considers usernames and knowledge based authentication (KBA) as public information, SMS and email notifications as insecure, and passwords as pre-breached. This reality renders knowledge based authenticators, SMS and email recovery, password history, complexity, and rotation controls useless.".

This was the draft version of NIST 800-63 B in 2016. "OOB using the PSTN (SMS or voice) is deprecated, and may no longer be allowed in future releases of this guidance."

https://web.archive.org/web/20160914183023/https://pages.nist.gov/800-63-3/sp800-63b.html

It has been revised in the latest version of NIST 800-63 B as of February 25, 2019.

"5.1.3.1 Out-of-Band Authenticators
[...]
Authenticate to a public mobile telephone network using a SIM card or equivalent that uniquely identifies the device. This method SHALL only be used if a secret is being sent from the verifier to the out-of-band device via the PSTN (SMS or voice)." 

with all the previous "OOB using the PSTN (SMS or voice) is deprecated" sentence removed.

https://pages.nist.gov/800-63-3/sp800-63b.html 

Will this render the "NIST 800-63 considers [..] SMS [..] notifications as insecure" incorrect?

**Comment by mastacheata** [comment]
> Will this render the "NIST 800-63 considers [..] SMS [..] notifications as insecure" incorrect?
It's still considered insecure as you need to pay attention to only use this option when the phone is the out-of-band-device. If the application itself is accessed from the phone, this isn't allowed by NIST. 

That's why it's inherently insecure. Obviously email is a lot more at risk because it's way more likely to have email on the very same device that you are using the web app with than receiving SMS.
But does the standard need a ranking of how insecure things are?

**Comment by tghosth** [comment]
Hi @vanderaj @jmanico @danielcuthbert. In the light of articles [like this](https://blogs.sap.com/2017/07/06/rollback-the-united-states-nist-no-longer-recommends-deprecating-sms-for-2fa/) and the discussion above, I am struggling to justify the statements "[NIST 800-63 considers...SMS and email notifications as insecure](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#control-objective)" and "[NIST considers email and SMS as plain text authentication channels, and they are likely to be removed from NIST 800-63](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v22-general-authenticator-requirements)"

Do you know what the source is or do you think we need to reword?

**Comment by jimfenton** [comment]
The goal of out-of-band authentication is to establish possession and control of a specific device. Email and SMS/voice to a VoIP number do not establish that, and therefore are not recognized by SP 800-63B for authentication.

SMS and voice telephony to non-VoIP numbers do establish this, but only weakly, due to risks including reassignment of the phone number and insecurity of the communications channel. They are therefore considered "restricted", meaning that alternative authenticator types need to be provided and that they might not be acceptable in the future.

The language changed between the draft and final versions because the term "deprecated" was misunderstood by many and because a more specific explanation was needed of what actions should be taken if use of this authenticator type was being considered.

[Note: I worked on SP 800-63B but I do not speak for NIST]

**Comment by tghosth** [comment]
Thanks @jimfenton that was really useful and helped me to find the relevant part of the NIST FAQ :)

I have modified the wording with commit https://github.com/OWASP/ASVS/commit/e4a396f13acf596ca246cd5e8a974cb9430a1428 and am closing the issue
