### ISSUE TITLE
3.1.2 and 7.1.1 duplicates?

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#560]
Is 3.1.2 `Verify the application never stores session tokens in log files.`
a duplicate of 7.1.1 `Verify that the application does not log credentials, session tokens or payment details.`?

**Comment by mastacheata** [comment]
I'd say yes, for simplicity's sake.
V7 has the headline error logging, but as far as I remember it covers all kinds of logging and that broader rule would then cover the specific one in V3 as well.

If you want to be nitpicking: V7 is about error logging, while 3.1.2 is generically about logging. Also 3.1.2 only covers log files, while 7.1.1 covers all kinds of logging mechanisms. 
It's obvious what is meant, though and therefore I'm not a fan of nitpicking 😅 

What solution would you suggest:
Remove the session logging from 7.1.1 or scratch 3.1.2.

**I'd probably favor removing the 3.1.2 - Especially since it doesn't cause a renumbering in order to close gaps.**

**Comment by elarlang** [comment]
I had the same issue in my "to-report" list.  So, +1 from me.

**recommendations**
  * remove 3.1.2 as it's covered by 7.1.1
  * in reality, for debuging/tracking/investigate there is still need to log session identifier somehow - in practice same hash of session id is logged instead of original session id. Maybe 7.1.1 should be finetuned something like "does not log" > "does not log as plain-text"

**Comment by elarlang** [comment]
> V7 is about error logging

@mastacheata Nooooo!  How many requirements in V7 describe error handling? 3. So, V7 title is with wrong pressure or a bit misleading.

**recommendation**
Rename V7 to "V7: Logging and Error Handling Verification Requirements"

alternative: we can flirt with idea to move entire "V7.4 Error Handling" to "V14: Configuration Verification Requirements" and leave V7 for pure logging.

**Comment by mastacheata** [comment]
> > V7 is about error logging
> 
> @mastacheata Nooooo! How many requirements in V7 describe error handling? 3. So, V7 title is with wrong pressure or a bit misleading.

If you quote me, quote me completely:
> If you want to be nitpicking: V7 is about error logging
That's about the headline, which could trick people into thinking these requirements would only apply to error logging.
I have no idea how other people perform a security analysis or even an audit based on the ASVS.
My first and so far only contact with the ASVS or any security standard for that matter was my own master's thesis that I just completed last week.

**Comment by tghosth** [comment]
Thanks for the feedback. I just committed a fix to remove 3.1.2, see: https://github.com/OWASP/ASVS/commit/884165baf86b93d2e45ffc49a4547a2c94b02233

I am going to close this issue so if you have a specific other item you would like to raise, please create a separate issue.
