### ISSUE TITLE
Where did X-XSS-Protection header requirement go?

### ISSUE THREAD

**Issue by davewichers** [OWASP/ASVS#642]
The ASVS 3.1 DRAFT had: "Verify that the X-XSS-Protection: 1; mode=block header is in place to enable browser reflected XSS filters."  But I can't find it in ASVS 4.0. Was it dropped on purpose?

**Comment by jmanico** [comment]
The general recommendation should be to disable this header I read recently...

https://twitter.com/philippederyck/status/1125303689088884736?s=21

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
See also [this commit](https://github.com/OWASP/ASVS/commit/751cdbce263ee3214e9783a33d10026d10d2c92c). If you don't mind, I am going to  close this issue for now.

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=43aa4523f1)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=43aa4523f1

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=43aa4523f1 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=43aa4523f1&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=43aa4523f1&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=43aa4523f1)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1
