### ISSUE TITLE
Minor: CSP used without definition in 5.3.6

### ISSUE THREAD

**Issue by davewichers** [OWASP/ASVS#643]
CSP is used in this requirement, and yet is previously defined as Credential Service Provider. Acronym collision!! :-(  However, for this requirement, it means Content Security Policy.   CSP is used, and defined properly in requirement 14.4.3 as well.

Content Security Policy is also used, without the acronym, in requirement 1.12.2.

**Comment by jmanico** [comment]
Ok that’s a epic catch. Very nice Dave!

Suggest we spell CSP out in both?

--
Jim Manico
@Manicode

**Comment by davewichers** [comment]
Spell out everywhere, with acronyms, because people might search for either? There is another acronym that includes CSP at the start, so there are 3 actually.

**Comment by jmanico** [comment]
Yea I like it. 👍🏼

--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=1aacc01e85)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=1aacc01e85

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=1aacc01e85 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=1aacc01e85&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=1aacc01e85&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=1aacc01e85)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=62f22fbe14)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=62f22fbe14

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=62f22fbe14 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=62f22fbe14&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=62f22fbe14&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=62f22fbe14)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1
