### ISSUE TITLE
10.2.1 What is  unauthorized phone home ?

### ISSUE THREAD

**Issue by belalena** [OWASP/ASVS#669]
10.2.1 
Verify that the application   source code and third party libraries do not contain unauthorized phone home   or data collection capabilities. Where such functionality exists, obtain the   user's permission for it to operate before collecting any data.

what is unauthorized phone home  ?

**Comment by tyler2cr** [comment]
throwing out a guess here: missing commas

"... do not contain unauthorized phone, home, or data collection capabilities."

_don't @ me about the oxford comma_ 😆

**Comment by sbani** [comment]
> unauthorized phone home
Is the case when the application or library you use sends a ping "home" to servers owned by the attacker/producer of the software.
Maybe it's called "phone home" because of ET, the movie? I'm not sure.

I thought about the difference between "phone home" and "data collection" and came to two example:

Some bulletin software used to "phone home" when you installed it because the developers wanted to know about new servers running their software. A simple anti-piracy feature. For sure, pirates immediately started to remove the "phone home" part of the software.
This is not "data collection" because there was no data involved. It was just a simple "ping" that enabled the bulletin developers to know about a new server.
In this case "phone home" is a feature and a fair try to reduce piracy.

But bad actors can make use of this too: They could leave a backdoor (or "bugdoor") in a library and make use of the "phone home" part to know about new vulnerable servers/applications. Could be left in an "update" feature. Bugdoor + "phone home" update feature is a pretty stealthy combination for an attacker.

I hope I could help you with my explanation.

**Comment by belalena** [comment]
Thanks a lot. Clear now
