### ISSUE TITLE
Should we prepare a 4.0.2

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#750]
Hi @vanderaj @jmanico @danielcuthbert @m8urnett,

Given that the OWASP Top 10 is now not scheduled until mid-Feb 2021 and @vanderaj has previously said he wants to wait until then to release 4.1, should we look at releasing a 4.0.2 in the mean time?

I think we would have to make this a limited changes version focusing on wording changes and fixes which don't add/remove requirements or significantly change their meaning.

What do you think?

**Comment by elarlang** [comment]
I link it here #666. So yes, please :)

**Comment by jmanico** [comment]
I think we’re closer to 4.1 with all the changes...

--
Jim Manico
@Manicode

**Comment by tghosth** [comment]
Hi @jmanico. I would also be happy for us to release a 4.1 based on all the changes we have so far plus resolving any other straightforward open issues.

However, the advantage of a 4.0.2 is that we can release non-breaking improvements relatively easilly without invalidating 4.0.1 and then make sure that 4.1 has a lot more of the open issues resolved.

**Comment by danielcuthbert** [comment]
I'm personally loathe to push a 4.1. So many have built policies and tools and methodologies and such around this, we have to be cautious about how such a change might impact many. a 4.0.x seems to be less intrusive imho

**Comment by jmanico** [comment]
I think that’s a fair perspective, I’m cool with 4.0.2 or 

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by vanderaj** [comment]
Thinking on this some more, I think there's an opportunity to do both.

Branch 4.0.2 - bug fixes only. Will require some work to back port the
fixes from master. The only thing I would countenance here is duplicate
issue removal, spelling fixes, and clarifications.

Branch 4.1 (master) - bug fixes and improvements.

That way, folks invested in 4.0 for the long term can have a fixed version,
and those who are able to move on can use 4.1. Even PCI DSS releases point
releases (3.2.1 etc), so we shouldn't be afraid of doing this.

thoughts? With OWASP Top 10 2020 being pushed to 2021, I am happy to push
this to completion depending on the team's thoughts on this matter?

thanks,
Andrew

**Comment by danielcuthbert** [comment]
Yah i like this approach, slow and precise :)

**Comment by jmanico** [comment]
Andrew is on it - 4.0.2 for small fixes and 4.1 for a big update.

But, all the edits that are in play - and there are a lot - tells me the current work is more appropriate for 4.1 since the changes are often more than small fixes.

So now I’m inclined to go right to 4.1 since that’s the work in progress, make sense? You agree Mr. Grossman?

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by elarlang** [comment]
If there is plan to get 4.1 done in near future (few months), then there is not too many points to use (time) resources for 4.0.2 release. Yes, it's the correct way, but.... 

From pen-test company perspective - with new ASVS release it requires some migration work anyway and if I can see new 4.1 release is coming, I would skip to take in use 4.0.2. I don't remember that someone wanted after ASVS 4.0 release pen-test using ASVS 3.0.1, except already fixed contracts before ASVS 4.0 release.

@tghosth  comment from issue #666 

> The target release date for the next OWASP Top 10 is mid-Feb 2021 so I doubt we will see a 4.1 before the end of April 2021.

If due date for 4.1 is not clear or is far away then I would like to get some version/release for fixes since March 2019. Other ways all the fixes are not usable for fixing ASVS version to pen-test contract (problem described in #666).

For small changes there should be goal/plan/strategy for new releases (cycle/interval). For example, wording fixes, typos etc once per quarter?

**Comment by tghosth** [comment]
@jmanico it looks like @vanderaj still sees 4.1 as not coming until after OWASP Top 10 2021 in almost another year. I think there are lots of relatively straightforward changes which could go into 4.0.2 and be released in the near future.

Unless anyone had any major objections or I have misunderstood @vanderaj, I will start investigating how we get the 4.0.2 branch prepared.

**Comment by jmanico** [comment]
Sounds good!

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
Ok, I have created a 4.0.2 branch and I have spent some time back-porting all the "bleeding edge" changes which I believe match @vanderaj requirements above

> The only thing I would countenance here is duplicate issue removal, spelling fixes, and clarifications.

@vanderaj @jmanico  @danielcuthbert  @m8urnett  please can you take a look at the changes and let me know if you approve. We can then decide if there is anything else we want to do before we release.

https://github.com/OWASP/ASVS/tree/v4.0.2

**Comment by ThunderSon** [comment]
Hello team :)
I'd like to give my PoV from multiple perspectives on the versioning.
**Maintainer PoV**
Having 2 branches that need constant follow-up and updating, on 2 different streams, is one hell of a task. The maintainer's task is now purely to keep those 2 sane and good. That's a lot of management.

**Contributor PoV**
If the change a contributor brings forward isn't a breaking change, they'll have to base on 2 branches. Good luck telling a new comer to git how to do that. That is going right up the maintainer's alley once again.

This is an unhealthy way to manage the repository. Why do I care about 4.0.2 while 4.1 is already pushing to come out? Typos and grammar? I'll just take the bleeding if I am looking for something other than 4.0
If 4.1 is released, it doesn't deprecate 4.0; set that clear in the release notes. Let the reader decide: "Do I want to move from 4.0 to 4.1? Is this move really worth it?" This is not for the project to worry about. This blocks productivity, contributions, and hold the project liable to:
1. Top 10 (WHY!). Let's say it gets pushed further till 2022 (not saying it will), what happens with ASVS? It better be v5.0 being released then. They are two non-related projects! MSTG x MASVS, that's a different talk for example, and I don't see those issues there.
2. Held hostage by companies using the project? It's the other way around. In WSTG we handled this by providing a versioning system that would allow people to reference whichever version they pick their work to reflect against. MASVS is referenced by a lot of companies. What they do is they set the milestones and contribution needs, and move things forward.

Nowadays I see lots of versioning everywhere. They update by the week, big projects. As someone using the project, I won't reference the bleeding edge, but more so the stable release I pick.

**Comment by jmanico** [comment]
This is a very mature argument. My initial instinct was to skip 4.0.2 and go right to 4.1 as well due to the extensive nature of the current changes.

I’d rather move fast and spit out a lot of versions until the standard stabilizes, which is just now starting to happen. ASVS is not really a standard anyhow, it’s more of a set of requirements to fork per our own description! :)

Aloha,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
I don't intend for there to be two parallel versions for very long, just as long as it takes to finalise a 4.0.2. 

If we decide we want to work on 4.0.2 more intensively, the other option is that we store the "requirement moving" changes on the side somewhere and reverse them out of master until we are ready to release a 4.1 with breaking changes.

Whilst a 4.0.2 version would not have loads of changes, there are some annoying wording things and broken links which it would be nice to fix :)

**Comment by vanderaj** [comment]
4.0.2 is in preparation. The process will be to commit changes for 4.0.2 to master, and then backport them to 4.0.2. No breaking changes (renaming, renumbering, reordering, removal) will occur in 4.0.2, only bug fixes, improved explanations, re-wording, and additional translations.

**Comment by ThunderSon** [comment]
Why is the [semver](https://semver.org/) system being used (x.y.z) and not applied? Why was my comment disregarded Andrew? Updating the minor version (y) does not say that you should be adding breaking changes whatsoever. That's what the major stands for (x).
Why not release 5.0.0 with OWASP Top 10 release and the project birthday? Semver is made to be used in a flexible manner. This implementation is the first time I've seen it.

v4.0.2 is not released and this is how it looks: `This branch is 32 commits ahead, 173 commits behind master.` 173 commits! 
As this is your project, this will be my last comment on this.

As for the actual release, I sent comments on the PR that @tghosth has opened to make things easier for review.

**Comment by jmanico** [comment]
ThunderSon,

I see that you have been doing a LOT of work on several projects and I'm 
worried that you are upset.

Can you take a moment and explain what is wrong and what happened? 
Andrew and all of us at ASVS are reasonable people and we want to make 
sure that your concerns are addressed. Sometimes we move to fast and 
make mistakes. Can you explain to us what happened?

Aloha, Jim

**Comment by ThunderSon** [comment]
In no way am I upset. This is not my project. I am trying to provide some help, if it is set on the sides, that's not on me. My comments are highly technical and discuss what are the issues. I even did a full review of 4.0.2; if I was upset I wouldn't have done that.

The concern is this: Currently, you are looking to release 4.0.2. Till February, there will be no other releases?
Currently, your main branch is ahead by 173 commits (that's a lot!). That's a whole MINOR version (minor being the 0->1, the y in semver) if not almost a MAJOR. Yet, you are trying to push a patch, while the gold is all ready to be released, and just needs a review to identify what's breaking and keep it for the MAJOR release.
And again, this project SHOULD NOT be related to Top 10. This is almost a standard (I still fail to see how this is not a standard, OWASP needs to own this space and is still failing to do that), and you are relating it to data statistics on what are the top risks? What is basing this dependency? Marketing? What are we trying to achieve?
Are we afraid of incrementing the numbers? I know how standards should grow, I am not saying to break things, but be reasonable in the release if you're looking to do releases. Patches (4.0.2 for example) are generally unplanned changes that are needed (grammar, links, etc.) that are released in a quick succession, not every 6 months. What you have right now is something ready for a minor release, and that's still being blocked.

@tghosth said "4.1 with breaking changes."; breaking changes are MAJOR (x), not a MINOR (y). So this should end up as 5.0.0, not as 4.1.0

I am trying to help with the semver nomenclature that is being used. I am trying to help with the quick rounds to help Josh with managing this project on GitHub (I know Elar and Jim are around too, but Josh is the main engine for the repository management).

Releasing this as `4.0.2` isn't anything of a critical issue that will bring the world to ruins. That's why I said that was my last comment (not putting additional effort on this as it's not worth it if the team is okay with it)

**Comment by elarlang** [comment]
I need to agree with @ThunderSon here and I link my arguments again here - #666. From @tghosth comment https://github.com/OWASP/ASVS/issues/666#issuecomment-530967509 I assume he does have pretty similar view to this topic.

This is something, where we should move. For a starter, we should get the v4.0.2 out to get some movement. 

I agree that next release in next year is not very good perspective. There are some known issues which requires restructuring, and it means this issue is/will be known more than a year before it actually get a chance to get some fix.

As I'm not anyhow officially related with OWASP or ASVS, I don't what kind of resource issues here may exists or why those milestones are like they are.

**Comment by jmanico** [comment]
I fully agree with ThunderSon as well.

Please decouple ASVS the OWASP Top Ten, it doesn’t make sense to keep them in parity.

Also, we have made so many changes to far I’d rather go to ASVS 4.1 or 5.0.

So as one of the ASVS leads I do concur with your logic, Sun of Thunder.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by elarlang** [comment]
But one clear recommendation at the moment I have - let's get v4.0.2 out and done and then we can open this release strategy discussion again. v4.0.2 should be clear priority no 1 at the moment and let's keep the focus on that.

**Comment by jmanico** [comment]
Why not skip it and go right to 4.1?

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by elarlang** [comment]
I don't think it's nice to drop plan on that late state. In case v4.0.2 is almost done, we should release it. It's list of small fixes. It's also kind of cleanup.

What is the realistic release date for v4.1 from now?

My argumentation and view I posted in may: https://github.com/OWASP/ASVS/issues/750#issuecomment-625983994 - now the situation with v4.0.2 is a bit different - it makes more sense to release it.

**Comment by ThunderSon** [comment]
4.0.2's PR is on the doors, let it out and push forward. The branch is there, the PR is ready, just close it and jump up, set a clear date for 4.1.0 and go for it, without waiting for 8 more months to release a minor.
Elar, hope that'd you be joining the teams soon, your contributions have been wonderful :)

**Comment by jmanico** [comment]
I’m with you now, I agree.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
There are lots of good points in these comments. The things I would say for now are: 

- 4.0.2 will be released in the near future and Andrew is working actively towards that
- the semantic versioning question is a good question which we need to think more about.
- please don't take the number of commits as a good indicator of changes or progress it may just be my bad github skills 🙃

Overall I greatly appreciate everyone's feedback on this. I sincerely hope no one feels ignored and we will work towards coming to a conclusion that makes sense.

**Comment by ossie-git** [comment]
Before releasing any updates, I think that it should be clearly highlighted and even **documented within the standard**:

- what types of changes are allowed in a PATCH change
- what types of changes are allowed in a MINOR change
- what types of changes are allowed in a MAJOR change 

That way we set expectations and can move forward in the future without any nasty surprises for anyone using the standard. And we don't have to repeat this discussion 1 - 2 years down the road. This can be added to the "**Using the ASVS**" section so everyone's on the same page, including those who don't look at GitHub Issues

**Comment by elarlang** [comment]
My proposal is - let's get this v4.0.2 out first. This is just a "small fixes release" and can be clearly written to the document.

All this release plan and ideology is must have, like I wrote already in #666, but please, AFTER v4.0.2 is out. At the moment it is really confusing - do we get this v4.0.2 out at all or we start again and again the same discussion (now in Twitter), should we release v4.0.2, or v4.1 or v5.0 etc. It's a bit demotivating to put effort into project if declared plans may change or dropped in last minute. If there is direction and the path declared and said out, please follow it (if there are no clear and huge reasons to choose other direction).

**Comment by elarlang** [comment]
Hello...

milestone for v4.0.2 (<https://github.com/OWASP/ASVS/milestone/7>) is passed, but here (in git repo) is complete silence.

Last commit to v4.0.2 branch was 16 days ago (<https://github.com/OWASP/ASVS/tree/v4.0.2/4.0>).

Was there some decision what I missed or what is the current plan now?

**Comment by elarlang** [comment]
Another week of silence. I think enough is enough. This is not really acceptable.

All key-persons have been active in Twitter. Why do we have silence here?

Big words <https://twitter.com/owasped> and opposite action. Expecting commitment and effort from community for what? To ignore them? Best way to get rid of people who had will to put their time and effort into the project.

**Comment by danielcuthbert** [comment]
@elarlang We all volunteer here, we don't get paid to do this and we balance life and kids and work too. 

I don't understand the comparison to Twitter, what does that have to do with a decision here on the direction of the project that potentially impacts thousands who use it? 

I don't recall when we agreed that the ASVS would be so quick to accept and push changes like you are implying, especially given the strange ugly world we are all trying to survive in right now. 

I appreciate your efforts but I do not appreciate how you are throwing a tantrum right now. It is counterproductive.

**Comment by danielcuthbert** [comment]
Back to actual ASVS stuff. 

I've no issue with a 4.0.2 release, it's a minor release that fixes small issues and bugs and won't break any process or tool currently using it. Ill look at making this happen this week, work/family/kids/surviving a global pandemic willing.

**Comment by elarlang** [comment]
All I was asking was communication. Ignorance/silence is not communication. I'm not the only one here waiting responses (example https://github.com/OWASP/ASVS/issues/812#issuecomment-655858090). If there is delay or decisions or changes or need for help, just say it out and it's all clear for others.

About "tantrum" - my English is not clearly good enough to "beautify" the message, so it can be too direct or "no filter" without actual intent to do so. I may not realize it, but there are no hard feelings in it. My goal is clearly to get things moving and done.

**Comment by danielcuthbert** [comment]
@elarlang as with all things OWASP and community, you have to understand that people come and go and give their time when they can. Normally this is quicker, but look at what is happening in the world right now. We are in a very ugly period of human history, most are worrying about losing their jobs, or trying to balance childcare and working from home. It's unprecedented pressure so yeah, sometimes the communications are slower than usual. It's not ignorance or ignoring, it's literally 'shit, i need to take care of the kids, ensure the house is clean, do work, worry about not getting fired and so on'

I, for one, truly **appreciate** what you do for the project and indeed so many others do. We aren't ignoring it at all, but sometimes comms will be slow for the above reasons. 

:) no hard feelings here at all, just take into account others time and how they might be struggling.

**Comment by vanderaj** [comment]
@ThunderSon The commits and backports are different whilst we are in the process of getting the release ready. Not all changes in master will be backported, and thus it will always be a little behind. Will it be 133 commits behind? Don't know. 

I think myself particularly are GitHub branch newbies, and we will make mistakes. We'll get it right with some care taken.

**Comment by tghosth** [comment]
We are now pushing for v4.0.2 at the start of August. I am closing this issue for now.
