### ISSUE TITLE
Cleanup verification descriptions from links

### ISSUE THREAD

**Issue by elarlang** [OWASP/ASVS#810]
## Links

There are also 77 requirements with links to <https://owasp.org/www-project-proactive-controls/#div-numbering>

```
$ grep -r "\[C" . | grep "\*\*" | wc -l
77
```

Those links are also not part of requirement text, maybe we should have another column in tables for them?

Problem (like described in #809) - if to use data in JSON format or want to use description text, then you need to cleanup requirement texts manually. Description text is not usable like it should be.

**Comment by tghosth** [comment]
I deliberately want these particular links in there. Taking discussion to #777 for now.

**Comment by elarlang** [comment]
74 of 320 requirements have this link. Maybe we should have this link in separate column in table like CWE and NIST, then it is not part of description text.

NIST reference is set to 69 requirements.

**Comment by tghosth** [comment]
I don't want to create too many columns...

**Comment by tghosth** [comment]
Reassigning this issue to @vanderaj as it kind of feeds into how we generate the different formats (makefile and #777) and if the existence of lots of links in the document makes a mess for things like the JSON or CSV formats

**Comment by jmanico** [comment]
Having a link inside of a requirement is a very bad idea. That means the requirement is not good enough as is, which is a problem. All links inside of requirements need to go in the summary at the bottom of the section if they are needed.

This is a really big deal that we fix this, in my opinion.

**Comment by jmanico** [comment]
> I don't want to create too many columns...

I agree @tghosth but links inside of requirements are a very bad idea. Can we move those links to "references" under each section with your blessing?

**Comment by tghosth** [comment]
These are not links to references, these are links to the relevant proactive control entry. It is more like a mapping. I think we need to agree a standard mapping format and maybe then move these to a different format.

**Comment by jmanico** [comment]
I strongly disagree Josh, I would like to take any links or references out of the requirement text itself, it means the requirement is not good enough as is. We can move the links to other parts of ASVS, just not in the requirement text itself.

**Comment by tghosth** [comment]
I think we do in fact agree :) If these were references for more information like in #664 then we should remove them (as I did in #664.)

In this case, these are not references for more information but rather just a mapping to track which requirements are in which proactive control. I also think that the mapping should be removed but we don't have a better solution for that yet, I have left the issue open so that we can deal with this at some point :)

**Comment by jmanico** [comment]
Ok cool. Can we add a new column to the ASVS for them? Like instead of

| **2.1.7** | [MODIFIED] Verify that passwords submitted during account registration and password change are checked against a set of breached passwords either locally (such as the top 50,000 to 100,000 most common passwords which match the system's password policy) or using an external API. If using an API a zero knowledge proof or other mechanism should be used to ensure that the plain text password is not sent or used in verifying the breach status of the password. Whenever there is a major third party breach of passwords, lock affected users and force a password change for the user to set a new non-breached password. ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering)) | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |

we do

| **2.1.7** | [MODIFIED] Verify that passwords submitted during account registration and password change are checked against a set of breached passwords either locally (such as the top 50,000 to 100,000 most common passwords which match the system's password policy) or using an external API. If using an API a zero knowledge proof or other mechanism should be used to ensure that the plain text password is not sent or used in verifying the breach status of the password. Whenever there is a major third party breach of passwords, lock affected users and force a password change for the user to set a new non-breached password. | ✓ | ✓ | ✓ | 521 | 5.1.1.2 |  ([C6](https://owasp.org/www-project-proactive-controls/#div-numbering))

?

**Comment by tghosth** [comment]
Eventually something like that but I'd rather leave it to the end near the next big release as it is a big change.

**Comment by elarlang** [comment]
Just a note, that CSV files from repository are created from latest release and are not updated when there are some changes in bleeding edge.

**Comment by ike** [comment]
After discussion with @jmanico, it seems like the best course is to:

- Remove the links from the CSV requirement text
- Add a structure to hold related links to the JSON requirements object

**Comment by jmanico** [comment]
Another option, if it's not too much trouble, is to add a new column to the CSV for links and just leave it empty if there is none. That's a reasonable path too if its not that much trouble!

**Comment by tghosth** [comment]
OK, in 5.0 all mappings including should be separated including proactive controls so I think this will get done so I am going to close this for now.
