### ISSUE TITLE
Make the need to fork ASVS more prominent

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#956]
Be sure to make the need to fork ASVS and start with level 1 items more prominent in the doc so beginners can get started with ASVS more easily.

**Comment by elarlang** [comment]
I just put this link here, as it probably is "spin-off" from this issue: https://github.com/OWASP/ASVS/issues/840

**Comment by csfreak92** [comment]
+1 on this idea. Since this is related to the original issue in 840 that I opened, may I know what I can do to make myself useful for this one?

**Comment by jmanico** [comment]
> +1 on this idea. Since this is related to the original issue in 840 that I opened, may I know what I can do to make myself useful for this one?

Would you like to propose some text to make the forking process more clear?

**Comment by csfreak92** [comment]
Sure, but before I do that I just want to ensure I understand. What do we mean by forking process? If it is a fork for beginners in ASVS, then are we talking about beginners on testing/development with the easier requirements to built and test which should be on that fork?

**Comment by csfreak92** [comment]
I totally agree with that, though looks like the forking process is already stated in the `As a Replacement for Off-the-shelf Secure Coding Checklists` paragraph here: https://github.com/OWASP/ASVS/blob/master/4.0/en/0x04-Assessment_and_Certification.md#as-a-replacement-for-off-the-shelf-secure-coding-checklists

Seems ok to me, but maybe we can improve it by moving this paragraph somewhere else in the page to make it stand out more?

**Comment by jmanico** [comment]
Exactly @csfreak92 this is the section I would like to expand on and make more prominent!

**Comment by csfreak92** [comment]
Gotcha, will work on improving text and placement of this section. I will submit any proposals here first. Cheers!

**Comment by jmanico** [comment]
You are awesome, Ralph! :)

**Comment by csfreak92** [comment]
Alright, here's what I have drafted so far. Let me know if it is a bit too much: 

I propose a change of title for this subsection from "As a Replacement for Off-the-self Secure Coding Checklists" to this: 
> `As a Specialized Secure Coding Checklist` 

as to reflect that we want ASVS to be a secure coding checklist, but through a fork which I later on described. 

Retaining this paragraph, but I am a bit confused with the second sentence, so probably needs more help and clarification what we mean by this part.  
`Many organizations can benefit from adopting the ASVS, by choosing one of the three levels, or by forking ASVS and changing what is required for each application risk level in a domain specific way. We encourage this type of forking as long as traceability is maintained, so that if an application has passed requirement 4.1, this means the same thing for forked copies as the standard as it evolves.`

Added this paragraph for more explanation about this ASVS usage and some guidelines for the forking process: 
`Ideally, every organization should have their own forked ASVS, select their requirements tailor-fitted for them and their applications. So if the organization is not using GraphQL, Websockets or SOAP web service on their applications, they should drop those sections from their forked ASVS. The forking process must start with looking at ASVS level 1 requirements as a baseline for the organization and then gradually move into ASVS level 2 or 3 as needed with based on their organization's risk level. Organizations must use their forked ASVS as a secure coding checklist for secure application development, preferably with guidance from security engineers or security architects alike. In this way, organizations will have a unified and clear secure coding checklist applicable for them and be used across all development teams. `

**Comment by csfreak92** [comment]
For the placement/arrangement in this page https://github.com/OWASP/ASVS/blob/master/4.0/en/0x04-Assessment_and_Certification.md, I kept reading through it and I noticed we have a subsection entitled "Testing Method", so I think it would be nice and practical to bundle this subsection with `As a Driver for Agile Application Security` and `As Detailed Security Architecture Guidance` and this `As a Replacement for Off-the-shelf Secure Coding Checklists or [with my new title up for discussion]`, then name all three of them in a subsection entitled "Secure Software Development". In this way, it stands out more compared to being just part of other uses for ASVS. I believe we want ASVS to be a guide for secure development as its main usage, so hopefully that brings it to a good point.

**Comment by cmlh** [comment]
Is there an existing fork that can be used as a reference implementation, such as an ["_Off-the-shelf Secure Coding Checklists_"](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x04-Assessment_and_Certification.md#as-a-replacement-for-off-the-shelf-secure-coding-checklists) that we intend to replace?

**Comment by csfreak92** [comment]
@jmanico, wordsmithing please on my draft? 

@cmlh, I am not aware of any such thing that we can use for reference implementation for that. Suggestions?

**Comment by cmlh** [comment]
I'd suggest we create a fork of ASVS if none exist then so it can be cited as a reference implementation.

**Comment by csfreak92** [comment]
@cmlh, does my draft proposal for JWT security practices in #1038 sound like similar to the fork you want to have? If not, maybe I need more ideas how to do your suggestion as I may not have understood it properly.

**Comment by cmlh** [comment]
I'm guessing it would depend on:

- [ ] the number of changes in the PR and;
- [ ] if they are portable to other web technologies (or JWT is a web technology specific new "Vx" heading) and;
- [ ] the number of forks are manageable i.e. reducing the number of forks to those aligned to major compliance standards such as https://github.com/OWASP/ASVS/issues/317#issuecomment-883844517 and https://github.com/OWASP/ASVS/issues/1039 for example.

We can apply the above criteria when the PR is made @csfreak92

**Comment by csfreak92** [comment]
Guys, did we have a way forward for this issue?

**Comment by elarlang** [comment]
This is big concept issue and is a bit part of v5.0 goals. https://github.com/OWASP/ASVS/issues/1127.

**Comment by tghosth** [comment]
@elarlang I think the forking concept remains valid regardless of the 5.0 direction although maybe the wording needs finalizing.

@csfreak92 please can you open a PR with your suggested changes and I will take a look.

**Comment by csfreak92** [comment]
^ Does that make the ASVS forking process clearer @jmanico? I was initially thinking of regrouping some of the subsections as I have mentioned earlier in the thread to make it more "Secure Software Development" focused as its main usage, but feel free to chime in what else I may have missed.

**Comment by jmanico** [comment]
It's great and time to merge :)

**Comment by tghosth** [comment]
Ok, now that I have seen the proposal, a thought occurred to me? Why are we talking about forking only in the "secure coding checklist" section. Surely forking the ASVS will be relevant to multiple use cases. I think the forking aspect should be somewhere higher up which clarifies that it relates to other use cases as well. For example, security architecture, testing.

**Comment by jmanico** [comment]
I think csfreak's work is a good first edit. After that is committed I would love another PR that clarifies is further. I'm with you Josh. :)

**Comment by csfreak92** [comment]
That is a great point, @tghosth. Yeah I think we can still bring that forking process point one hierarchy higher.

**Comment by tghosth** [comment]
so please update the PR and then tag me :)

**Comment by tghosth** [comment]
I think we are done with this now.
