### ISSUE TITLE
Add a new Level 3 requirement on HSTS Preloading

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#966]
Addressing comment from https://github.com/OWASP/ASVS/issues/963#issuecomment-816099739

**Comment by elarlang** [comment]
What is this issue? Just for adding `[MODIFIED]` label and should be already closed or I totally miss the point? :)

**Comment by jmanico** [comment]
Proloading is a separate issue described here: https://hstspreload.org/ - This is a specialized portion of the HSTS standard to allow your site to be preloaded in the browser software so its just not possible to even try to make a HTTP request to a site, even before you visit the site and get a HSTS response header (hence, pre-loading)

**Comment by cmlh** [comment]
I propose to cite **HSTS** as a control for PCI-DSS v3.2.1 Requirements from Issue https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114:

- [2.2.3](https://user-images.githubusercontent.com/136826/116527891-81febb00-a91e-11eb-9bce-5441194ced91.png)
- [2.3](https://user-images.githubusercontent.com/136826/116528176-d99d2680-a91e-11eb-93a8-4799d302ec47.png)

I propose to cite HSTS **Preloading** as a control for [PCI-DSS v3.2.1 Requirement 4.1](https://user-images.githubusercontent.com/136826/116528344-1406c380-a91f-11eb-8816-3bc5712d97ce.png)

Can @jmanico and/or @tghosth and/or other Project Manager(s) approve the above so I can create the Pull Request(s) or instruct me to create a related new issue to https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114

**Comment by elarlang** [comment]
At the moment personally I can not understand, what is your proposal. I share my "template" what I have used sometimes:
```
Proposal:
* [Label](https://github.com/OWASP/ASVS/blob/master/CONTRIBUTING.md): todo
* Category: todo
  * todo: no changes or why it changes
* Id: todo
  * todo: no changes or why it changes
* Requirement: todo
  * todo: no changes or why it changes
* Levels: todo
  * todo: no changes or why it changes
* NIST: todo
  * todo: for some V2 and V3 requirements
* CWE: todo
  * todo: comments if needed
```

**Comment by cmlh** [comment]
> At the moment personally I can not understand, what is your proposal. I share my "template" what I have used sometimes:

Can I reuse this as [template for issues](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) with credit to you @elarlang ?

https://github.com/OWASP/ASVS/issues/966#issuecomment-833353752 is to support the modification of [Appendix D of ASVS v3.0](https://user-images.githubusercontent.com/136826/50191893-0b337980-0384-11e9-9781-ddc35239a7b8.png) and insertion into  [ASVS 4.1](https://github.com/OWASP/ASVS/issues/317#issuecomment-797796017) . 

Please let me know if I need to [create a new but related issue](https://github.com/OWASP/ASVS/issues/new/choose) to #317 (comment)?

**Comment by elarlang** [comment]
## offtopic - issue template

You can use this template wherever you want :) At the moment, till we don't have clear development process written anywhere, this template should be "all discussions in issues should reach to that proposal (template)".

## on topic

Current issue is spin-off from #963, and as I understand, direction is to make separate "Level 3" requirement additionally for current 14.4.5 with recommending using "preload".

Maybe I didn't investigate enough all the links you provided, but I'm not sure those are all related. That's why I shared my template - with that structure it is clear from ASVS point of view, what kind of change you propose.

**Comment by jmanico** [comment]
I support a level 3 requirement around preloading, but I prefer not to add PCI-DSS text in it. PCI-DSS does not discuss preloading at all. So @cmlh if you want to take a stab at this requirement, please give it a run here in the issue tracker first. I do not think we need PCI citations attached to the requirement though.

**Comment by cmlh** [comment]
[PCI-DSS v3.2.1 Requirement 4.1](https://user-images.githubusercontent.com/136826/116528344-1406c380-a91f-11eb-8816-3bc5712d97ce.png) states  "_Only trusted keys and certificates are accepted_." which is the same control enforced by Preloading. 

I have marked HSTS as the control for PCI-DSS v3.2.1 Requirements [2.2.3](https://user-images.githubusercontent.com/136826/116527891-81febb00-a91e-11eb-9bce-5441194ced91.png) and [2.3](https://user-images.githubusercontent.com/136826/116528176-d99d2680-a91e-11eb-93a8-4799d302ec47.png) within the Markdown Task List at the end of Issue https://github.com/OWASP/ASVS/issues/317#issuecomment-829077114

Would @jmanico support that I forked ASVS to support PCI-DSS v3.2.1?

**Comment by elarlang** [comment]
> "_Only trusted keys and certificates are accepted_." which is the same control enforced by Preloading.

Extra parameter `preload` in `Strict-Transport-Security` headers sets limitation to browser, that domains in "preload" list can be accessed using HTTPS connection. That's it. Nothing about certificates.

**Comment by cmlh** [comment]
> Extra parameter `preload` in `Strict-Transport-Security` headers sets limitation to browser, that domains in "preload" list can be accessed only using HTTPS connection. That's it. Nothing about certificates.

The preloaded https://source.chromium.org/chromium/chromium/src/+/master:net/http/transport_security_state_static.json lists the `pinsets` of trusted certificates.

**Comment by elarlang** [comment]
To force browsers using / to get effect from "preload" attribute, your domain must have valid certificate first. From that perspective I can understand your quote "Only trusted keys and certificates are accepted".

Scope for the issue is `Strict-Transport-Security` response header. Valid certificates are required by V9.1.* requirements and those are required also without "preload" attribute in `Strict-Transport-Security` header. Look them separately.

Therefore I repeat my recommendation in https://github.com/OWASP/ASVS/issues/966#issuecomment-833359450 . Please write proposal in "ASVS format". If you through a lot of links and some out of context piece of information, it's complicated to understand, what is your message or what is your proposal.

Or other option in this case - you can see, that this requirement will be in place in the future, just follow the issue to see, how and when it happens.

**Comment by cmlh** [comment]
I don't believe @elarlang Issue Template would be applicable in this case as I consider my matter closed as @jmanico responded with https://github.com/OWASP/ASVS/issues/966#issuecomment-833615779 below

> I do not think we need PCI citations attached to the requirement though.

I therefore intend to proceed with https://github.com/OWASP/ASVS/issues/966#issuecomment-833960359

> Would @jmanico support that I forked ASVS to support PCI-DSS v3.2.1?

Please don't let this discourage @elarlang from pursing the [Issue's Template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by elarlang** [comment]
Alternative for adding new requirement, it's possible to use solution like it's done with [3.2.2](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x12-V3-Session-management.md)

`+` It does not feel like duplicate requirement, which may be confusing
`-` it is maybe not that clear to read from requirement text alone.

**Comment by jmanico** [comment]
Duplicate for https://github.com/OWASP/ASVS/issues/966

**Comment by jmanico** [comment]
Preloading is a little bit too deep for now, so closing this out.
